### ISSUE TITLE
In-App Purchases validation fails with "Request timeout"

### ISSUE THREAD

**Issue by valeryvaskabovich** [ParsePlatform/parse-server#2225] opened 2016-07-07 06:10 UTC
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

### Issue Description

Sending the request to 'validate_purchase' from iOS device (Parse iOS SDK v1.13.0) every time fails with 'Request timeout' in server logs and HTML web-page in responseString (please see below)

### Steps to reproduce

1. Make purchase on iOS device to obtain valid receipt
2. Send request to 'validate_purchase' with correct productIdentifier & receipt

#### Expected Results

PFProduct 'download' file starts downloading

#### Actual Outcome

Request fails with "Request timeout" in server logs and HTML web-page in responseString in -[PFURLSessionJSONDataTaskDelegate _taskDidFinish]

### Environment Setup

- **Server**
  - parse-server version: 2.2.15
  - Localhost or remote server: Heroku

- **Database**
  - Localhost or remote server: mLab

### Logs/Trace

Logs in heroku console:

`at=error code=H12 desc="Request timeout" method=POST path="/parse/validate_purchase" host=mytestapp.herokuapp.com request_id=3d2ed6f9-d18b-4b8d-a8a2-addb60afe45c fwd="93.84.7.35" dyno=web.1 connect=0ms service=30257ms status=503 bytes=0 
`

self.responseString value in [PFURLSessionJSONDataTaskDelegate _taskDidFinish]:

`<!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <style type="text/css"> html, body, iframe { margin: 0; padding: 0; height: 100%; } iframe { display: block; width: 100%; border: none; } </style> <title>Application Error</title> </head> <body> <iframe src="//s3.amazonaws.com/heroku_pages/error.html"> <p>Application Error</p> </iframe> </body> </html>`

**Comment by flovilmart** [comment] 2016-07-08 17:46
Can you run the server with VERBOSE=1 and post the logs related to the call? 
That will help debugging

**Comment by valeryvoskobovich** [comment] 2016-07-08 22:23
Yep, but I'm not sure that I'm in the position to send real productIdentifier and related info like appId in public. May I change it for now to some random value (I'm pretty sure that AppStore validation should return error in the case of random value and validate_purchase request should not be failed with timeout)?

`2016-07-08T22:14:58.251623+00:00 app[web.1]: verbose: POST /parse/validate_purchase { host: 'mytestapp.herokuapp.com',
2016-07-08T22:14:58.251635+00:00 app[web.1]:   'x-parse-session-token': 'r:<current_sessionToken>',
2016-07-08T22:14:58.251637+00:00 app[web.1]:   'x-parse-os-version': '9.3.2 (13F69)',
2016-07-08T22:14:58.251637+00:00 app[web.1]:   'x-parse-installation-id': '<installId>',
2016-07-08T22:14:58.251636+00:00 app[web.1]:   'x-parse-application-id': '<my_appId>',
2016-07-08T22:14:58.251638+00:00 app[web.1]:   'accept-language': 'en-gb',
2016-07-08T22:14:58.251633+00:00 app[web.1]:   connection: 'close',
2016-07-08T22:14:58.251634+00:00 app[web.1]:   accept: '*/*',
2016-07-08T22:14:58.251640+00:00 app[web.1]:   'user-agent': 'RW/27 CFNetwork/758.4.3 Darwin/15.5.0',
2016-07-08T22:14:58.251638+00:00 app[web.1]:   'accept-encoding': 'gzip, deflate',
2016-07-08T22:14:58.251639+00:00 app[web.1]:   'content-type': 'application/json; charset=utf-8',
2016-07-08T22:14:58.251642+00:00 app[web.1]:   'x-forwarded-for': '37.17.7.38',
2016-07-08T22:14:58.251641+00:00 app[web.1]:   'x-parse-app-build-version': '27',
2016-07-08T22:14:58.251644+00:00 app[web.1]:   via: '1.1 vegur',
2016-07-08T22:14:58.251644+00:00 app[web.1]:   'x-forwarded-port': '443',
2016-07-08T22:14:58.251645+00:00 app[web.1]:   'connect-time': '1',
2016-07-08T22:14:58.251649+00:00 app[web.1]:     "__type": "Bytes",
2016-07-08T22:14:58.251685+00:00 app[web.1]:   },
2016-07-08T22:14:58.251647+00:00 app[web.1]:   'content-length': '8901' } {
2016-07-08T22:14:58.251641+00:00 app[web.1]:   'x-parse-app-display-version': '1.9',
2016-07-08T22:14:58.251642+00:00 app[web.1]:   'x-request-id': '0efa748e-c3e7-4dd9-8d5e-dc9a020f1a30',
2016-07-08T22:14:58.251643+00:00 app[web.1]:   'x-forwarded-proto': 'https',
2016-07-08T22:14:58.251646+00:00 app[web.1]:   'x-request-start': '1468016097967',
2016-07-08T22:14:58.251683+00:00 app[web.1]:     "base64": "MIIZnQYJKoZIhvcNAQcCoIIZjjCCGYoCAQExCzAJBgUrDgMCGgUAMIIJPgYJKoZIhvcNAQcBoIIJLwSCCSsxggknMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgELAgEBBAMCAQAwCwIBDgIBAQQDAgFqMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQMCAQEEBAwCMjcwDAIBCgIBAQQEFgI0KzANAgENAgEBBAUCAwFgvjANAgETAgEBBAUMAzEuMDAOAgEJAgEBBAYCBFAyNDcwGAIBBAIBAgQQRRtstVMgFt31G1WFRGKK1jAaAgECAgEBBBIMEGNvbS5sb25nc3dvcmQucncwGwIBAAIBAQQTDBFQcm9kdWN0aW9uU2FuZGJveDAcAgEFAgEBBBQh/3zSenrMSUykcFBUlZ6AGJUdaDAeAgEMAgEBBBYWFDIwMTYtMDctMDhUMjI6MTQ6NTdaMB4CARICAQEEFhYUMjAxMy0wOC0wMVQwNzowMDowMFowRwIBBwIBAQQ/tcyJt6np1/3xadd8AWMv2RZhFY//z249ZPrCRtDm7AAO4XkQV6tSmi78Ktjt7NZTe4l4qO6TdCBk4woszHjQMFECAQYCAQEESVnnTaatq95VxCn1Y8CKPA5ybELDsffTOHhe6Al42t3xnrh2pKL/BHh8HZXUKkvcz56xlC9wlqekRB3K/Vtgvy3o2XaGeT1W4H0wggFmAgERAgEBBIIBXDGCAVgwCwICBqwCAQEEAhYAMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQEwDAICBq4CAQEEAwIBADAMAgIGrwIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwGwICBqcCAQEEEgwQMTAwMDAwMDE3MTA5NTIzODAbAgIGqQIBAQQSDBAxMDAwMDAwMTcxMDk1MjM4MB8CAgaoAgEBBBYWFDIwMTUtMDktMDlUMDY6MDU6MjlaMB8CAgaqAgEBBBYWFDIwMTUtMDktMDlUMDY6MDU6MjlaMCwCAgamAgEBBCMMIWNvbS5sb25nc3dvcmQucncuZGV2aWNlLmJ1Z21hZ25ldDCCAWwCARECAQEEggFiMYIBXjALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBATAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAbAgIGpwIBAQQSDBAxMDAwMDAwMTcwOTQzNjE4MBsCAgapAgEBBBIMEDEwMDAwMDAxNzA5NDM2MTgwHwICBqgCAQEEFhYUMjAxNS0wOS0wOFQwNzo0NjozNlowHwICBqoCAQEEFhYUMjAxNS0wOS0wOFQwNzo0NjozNlowMgICBqYCAQEEKQwnY29tLmxvbmdzd29yZC5ydy5kZXZpY2Uud2F0ZXJyZXNpc3RhbmNlMIIBbAIBEQIBAQSCAWIxggFeMAsCAgasAgEBBAIWADALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEBMAwCAgauAgEBBAMCAQAwDAICBq8CAQEEAwIBADAMAgIGsQIBAQQDAgEAMBsCAganAgEBBBIMEDEwMDAwMDAxNzEwOTQ3MTcwGwICBqkCAQEEEgwQMTAwMDAwMDE3MTA5NDcxNzAfAgIGqAIBAQQWFhQyMDE1LTA5LTA5VDA2OjAwOjU1WjAfAgIGqgIBAQQWFhQyMDE1LTA5LTA5VDA2OjAwOjU1WjAyAgIGpgIBAQQpDCdjb20ubG9uZ3N3b3JkLnJ3LmRldmljZS53YXRlcnJlc2lzdGFuY2UwggFsAgERAgEBBIIBYjGCAV4wCwICBqwCAQEEAhYAMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQEwDAICBq4CAQEEAwIBADAMAgIGrwIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwGwICBqcCAQEEEgwQMTAwMDAwMDE3MTA5NTI3ODAbAgIGqQIBAQQSDBAxMDAwMDAwMTcxMDk1Mjc4MB8CAgaoAgEBBBYWFDIwMTUtMDktMDlUMDY6MDY6MTZaMB8CAgaqAgEBBBYWFDIwMTUtMDktMDlUMDY6MDY6MTZaMDICAgamAgEBBCkMJ2NvbS5sb25nc3dvcmQucncuZGV2aWNlLndhdGVycmVzaXN0YW5jZTCCAWwCARECAQEEggFiMYIBXjALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBATAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAbAgIGpwIBAQQSDBAxMDAwMDAwMjIyNjQ5MDk3MBsCAgapAgEBBBIMEDEwMDAwMDAyMjI2NDkwOTcwHwICBqgCAQEEFhYUMjAxNi0wNy0wOFQyMjoxNDo1N1owHwICBqoCAQEEFhYUMjAxNi0wNy0wOFQyMjoxNDo1N1owMgICBqYCAQEEKQwnY29tLmxvbmdzd29yZC5ydy5kZXZpY2Uud2F0ZXJyZXNpc3RhbmNloIIOZTCCBXwwggRkoAMCAQICCA7rV4fnngmNMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE1MTExMzAyMTUwOVoXDTIzMDIwNzIxNDg0N1owgYkxNzA1BgNVBAMMLk1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKXPgf0looFb1oftI9ozHI7iI8ClxCbLPcaf7EoNVYb/pALXl8o5VG19f7JUGJ3ELFJxjmR7gs6JuknWCOW0iHHPP1tGLsbEHbgDqViiBD4heNXbt9COEo2DTFsqaDeTwvK9HsTSoQxKWFKrEuPt3R+YFZA1LcLMEsqNSIH3WHhUa+iMMTYfSgYMR1TzN5C4spKJfV+khUrhwJzguqS7gpdj9CuTwf0+b8rB9Typj1IawCUKdg7e/pn+/8Jr9VterHNRSQhWicxDkMyOgQLQoJe2XLGhaWmHkBBoJiY5uB0Qc7AKXcVz0N92O9gt2Yge4+wHz+KO0NP6JlWB7+IDSSMCAwEAAaOCAdcwggHTMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyMDQwHQYDVR0OBBYEFJGknPzEdrefoIr0TfWPNl3tKwSFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEeBgNVHSAEggEVMIIBETCCAQ0GCiqGSIb3Y2QFBgEwgf4wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYLAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAA2mG9MuPeNbKwduQpZs0+iMQzCCX+Bc0Y2+vQ+9GvwlktuMhcOAWd/j4tcuBRSsDdu2uP78NS58y60Xa45/H+R3ubFnlbQTXqYZhnb4WiCV52OMD3P86O3GH66Z+GVIXKDgKDrAEDctuaAEOR9zucgF/fLefxoqKm4rAfygIFzZ630npjP49ZjgvkTbsUxn/G4KT8niBqjSl/OnjmtRolqEdWXRFgRi48Ff9Qipz2jZkgDJwYyz+I0AZLpYYMB8r491ymm5WyrWHWhumEL1TKc3GZvMOxx6GUPzo22/SGAGDDaSK+zeGLUR2i0j0I78oGmcFxuegHs5R0UwYS/HE6gwggQiMIIDCqADAgECAggB3rzEOW2gEDANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwMjA3MjE0ODQ3WhcNMjMwMjA3MjE0ODQ3WjCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMo4VKbLVqrIJDlI6Yzu7F+4fyaRvDRTes58Y4Bhd2RepQcjtjn+UC0VVlhwLX7EbsFKhT4v8N6EGqFXya97GP9q+hUSSRUIGayq2yoy7ZZjaFIVPYyK7L9rGJXgA6wBfZcFZ84OhZU3au0Jtq5nzVFkn8Zc0bxXbmc1gHY2pIeBbjiP2CsVTnsl2Fq/ToPBjdKT1RpxtWCcnTNOVfkSWAyGuBYNweV3RY1QSLorLeSUheHoxJ3GaKWwo/xnfnC6AllLd0KRObn1zeFM78A7SIym5SFd/Wpqu6cWNWDS5q3zRinJ6MOL6XnAamFnFbLw/eVovGJfbs+Z3e8bY/6SZasCAwEAAaOBpjCBozAdBgNVHQ4EFgQUiCcXCam2GGCL7Ou69kdZxVJUo7cwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290LmNybDAOBgNVHQ8BAf8EBAMCAYYwEAYKKoZIhvdjZAYCAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAE/P71m+LPWybC+P7hOHMugFNahui33JaQy52Re8dyzUZ+L9mm06WVzfgwG9sq4qYXKxr83DRTCPo4MNzh1HtPGTiqN0m6TDmHKHOz6vRQuSVLkyu5AYU2sKThC22R1QbCGAColOV4xrWzw9pv3e9w0jHQtKJoc/upGSTKQZEhltV/V6WId7aIrkhoxK6+JJFKql3VUAqa67SzCu4aCxvCmA5gl35b40ogHKf9ziCuY7uLvsumKV8wVjQYLNDzsdTJWk26v5yZXpT+RN5yaZgem8+bQp0gF6ZuEujPYhisX4eOGBrr/TkJ2prfOv/TgalmcwHFGlXOxxioK0bA8MFR8wggS7MIIDo6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNjA0MjUyMTQwMzZaFw0zNTAyMDkyMTQwMzZaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnRymacJGsR0KO75Bsqwx+VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV/X5vyJQO6VY9NXQ3xZDUjFUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw+dPfMrSSgayP7OtbkO2V4c1ss9tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4++NwzeajTEV+H0xrUJZBicR0YgsQg0GHM4qBsTBY7FoEMoxos48d3mVz/2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAXowggF2MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjCCAREGA1UdIASCAQgwggEEMIIBAAYJKoZIhvdjZAUBMIHyMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wDQYJKoZIhvcNAQEFBQADggEBAFw2mUwteLftjJvc83eb8nbSdzBPwR+Fg4UbmT1HN/Kpm0COLNSxkBLYvvRzm+7SZA/LeU802KI++Xj/a8gH7H05g4tTINM4xLG/mk8Ka/8r/FmnBQl8F0BWER5007eLIztHo9VvJOLr0bdw3w9F4SfK8W147ee1Fxeo3H4iNcol1dkP1mvUoiQjEfehrI9zgWDGG1sJL5Ky+ERI8GA4nhX1PSZnIIozavcNgs/e66Mv+VNqW2TAYzN39zoHLFbr2g8hDtq6cxlPtdk2f8GHVdmnmbkyQvvY1XGefqFStxu9k0IkEirHDx22TZxeY8hLgBdQqorV2uT80AkHN7B1dSExggHLMIIBxwIBATCBozCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIDutXh+eeCY0wCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAQCOT+HDkulxMBQQ9p3OVWvbkXFcOhlMP3FyZz5O0NtVXuDHwX5n+lsnuFa8VVkRl31T8MkINqmEVPK7bLlwONdFsioxCYP9hTm/3KUtNfbj/wTnQbL6sozP2SzkpQES8pdXmU4hLx1pqoie8paOn3HN61ZkFzfrQv8pThuae1cgBpW0neqq75QVOIY/BrH7rzoJNcclec0NHurZs3yIdidIjuMuIp2i1LScxooPdBrIS9yzUyHuReJ0RZrEIJlwzvMmndirH/X46LqntX24dH6wWqcHRxAP6QAPQyVeRLRI1ldi2P5q4Ga1nUMK9k3y0cc5LX7/vhimW6nVM2Jfnv0Z"
2016-07-08T22:14:58.251646+00:00 app[web.1]:   'total-route-time': '0',
2016-07-08T22:14:58.251648+00:00 app[web.1]:   "receipt": {
2016-07-08T22:14:58.251686+00:00 app[web.1]:   "productIdentifier": "com.myproductidentifier"
2016-07-08T22:14:58.251687+00:00 app[web.1]: }
2016-07-08T22:15:28.175789+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/validate_purchase" host=mytestapp.herokuapp.com request_id=0efa748e-c3e7-4dd9-8d5e-dc9a020f1a30 fwd="37.17.7.38" dyno=web.1 connect=1ms service=30206ms status=503 bytes=0`

**Comment by valeryvoskobovich** [comment] 2016-07-11 09:52
I assume the problem is somewhere inside getFileForProductIdentifier because:
1. If you enable NODE_ENV=test, the request will also fail with the same timeout error.
2. If you send invalid productIdentifier/receipt Apple servers will respond very fast with the following error: 
`{"status":21002,"error":"The data in the receipt-data property was malformed or missing."}`

P.S. My fileKey & S3Adapter are configured correctly because I have an access to all files from hosted Parse & upload new files to S3 cloud

**Comment by valeryvoskobovich** [comment] 2016-07-11 20:49
I made some debugging and my results are:
1. The issue is related to validating SANDBOX receipt, and receipt is missing when passing to `validateWithAppStore(IAP_SANDBOX_URL)`. Correct call will be `validateWithAppStore(IAP_SANDBOX_URL, receipt);`
2. Any of 2 Promise callbacks (in case of success and in case of error) is not called after sending receipt to SANDBOX url.

**Comment by flovilmart** [comment] 2016-07-11 20:53
@valeryvoskobovich thanks for the debugging, do you think you could work out a pull request?

**Comment by valeryvoskobovich** [comment] 2016-07-11 20:55
@flovilmart I'll try but I'm not a NodeJS developer :)

**Comment by flovilmart** [comment] 2016-07-11 20:56
@valeryvoskobovich I'm wasn't a node.js developer either :) I'm sure you'll work something out

**Comment by flovilmart** [comment] 2016-07-11 21:07
I believe you mean here: https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/IAPValidationRouter.js#L41 we don't put the receipt back

**Comment by valeryvoskobovich** [comment] 2016-07-11 21:10
Yes, that's right. But after the second request neither https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/IAPValidationRouter.js#L87 nor https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/IAPValidationRouter.js#L89 isn't called

**Comment by flovilmart** [comment] 2016-07-11 21:13
even if you set the receipt option?

**Comment by valeryvoskobovich** [comment] 2016-07-11 21:16
Yep. I had to implement inner promise callbacks to Sandbox request to start getting file

**Comment by flovilmart** [comment] 2016-07-11 21:17
alright :)

**Comment by valeryvoskobovich** [comment] 2016-07-11 21:23
Now I have something like this which is working (as it seems to me):

`    function successCallback() {
        return getFileForProductIdentifier(productIdentifier, req);
    };

    function errorCallback(error) {
        return Promise.resolve({response: appStoreError(error.status) });
    }
    
    return validateWithAppStore(IAP_PRODUCTION_URL, receipt).then( () => {
      return successCallback();
    }, (error) => {

      if (error.status == 21007) {
        return validateWithAppStore(IAP_SANDBOX_URL, receipt).then( () => {
            return successCallback();
          }, (error) => {
            return errorCallback(error);
          }
        );
      } 

      return errorCallback(error);
    });`

**Comment by valeryvoskobovich** [comment] 2016-07-11 21:36
Here is my changes
https://github.com/valeryvoskobovich/parse-server/commit/a91d9135b8bf1b10556eb2829dc0c7fc8ad66394

**Comment by flovilmart** [comment] 2016-07-11 21:37
Alright, open a PR and we'll move the conversation over there for implementation details

**Comment by valeryvaskabovich** [comment] 2016-07-11 22:10
@flovilmart my PR is ready, waiting for your comments

**Comment by flovilmart** [comment] 2016-07-11 23:36
On it :)

**Comment by flovilmart** [comment] 2016-07-11 23:39
Fixed by #2253

**Closed by flovilmart** 2016-07-11 23:39 UTC
Labels: troubleshooting

**Comment by valeryvaskabovich** [comment] 2016-07-12 08:49
@flovilmart Could you make a new parse-server release with my fix?
