### ISSUE TITLE
Not receiving email link from Parse export

### ISSUE THREAD

**Issue by Boston0070** [ParsePlatform/parse-server#3435] opened 2017-01-26 02:47 UTC
Been about 30 mins, no link for export data...

**Comment by Boston0070** [comment] 2017-01-26 04:17
On the old dashboard, not new beta, just says "Waiting to begin..."
Tried on new dashboard and says we will send link when data ready. 
Been over an hour now...

**Comment by NatanRolnik** [comment] 2017-01-26 08:28
@Boston0070 please go to https://parse.com/help and report your issue.
As an alternative, you can checkout the code from @davimacedo [in this PR](https://github.com/ParsePlatform/parse-server/pull/3046) and run it locally. Your own Parse Server will be able to export the data for you.

Closing as this is not a bug in the open source Parse Server.

**Closed by NatanRolnik** 2017-01-26 08:28 UTC

**Comment by codegefluester** [comment] 2017-01-26 14:42
Adding to what @NatanRolnik said, the export feature of parse.com is not supported anymore and you should use the official migration tool that we offer to move your data from parse.com to your own database.

If you have already migrated your app's database I recommend to simply make a dump of the DB directly from MongoDB.

**Comment by Boston0070** [comment] 2017-01-26 23:24
Using migration tool, thanks!
