### ISSUE TITLE
The CRC dependency requires c++11 and eb is unable to install it

### ISSUE THREAD

**Issue by tenshihan** [ParsePlatform/parse-server#1082] opened 2016-03-17 17:47 UTC
Can you revert to the normal crc library instead of the one that needs native bindings?

**Comment by tenshihan** [comment] 2016-03-17 17:48
specifically sse4_crc32

**Comment by flovilmart** [comment] 2016-03-31 23:47
what package is causing that issue?

**Comment by flovilmart** [comment] 2016-04-01 01:27
this seems to be parse-server-gcs-adapter, I'll mark it as an optional dependency.

**Comment by tenshihan** [comment] 2016-04-01 16:50
Cool, tell me when I can redeploy.

**Comment by flovilmart** [comment] 2016-04-01 16:53
That's not as easy as it seems...

**Comment by tenshihan** [comment] 2016-04-01 16:57
Oh. Is there anything I can do to help?

**Comment by flovilmart** [comment] 2016-04-01 16:58
Just check if setting parse-server-gcs adapter as optional makes it work for you, and the big problem are the imports in src/index.js.

**Comment by tenshihan** [comment] 2016-04-01 16:59
I'm using this as an express server, do you think there will be additional problems?

**Comment by tenshihan** [comment] 2016-04-01 17:00
I can replicate the problem by throwing a fresh install of cent 6.7 into vagrant, I will do that tonight and update this thread with my changes.

**Comment by flovilmart** [comment] 2016-04-02 04:08
http://stackoverflow.com/questions/34084814/npm-error-when-deploying-nodejs-to-elastic-beanstalk

**Comment by lasse-skogland** [comment] 2016-04-02 14:34
Username: tenshihan
Legal Name: Lasse Skogland
Email: lasse.skogland@gmail.com
Twitter: @lasseskogland
Face:
![skogland](https://cloud.githubusercontent.com/assets/18231475/14226911/e775ae8e-f8df-11e5-8ebb-ed1262b71bcd.jpg)

**Comment by flovilmart** [comment] 2016-04-02 15:10
Closing as duplicate of #1331

Please post relevant logs to the newly created issue

**Closed by flovilmart** 2016-04-02 15:10 UTC

**Comment by Rukachan** [comment] 2016-04-02 16:16
@flovilmart It can't be a duplicate if it was created first.

**Comment by danpantry** [comment] 2016-04-02 17:39
> Duplicate: one of two or more identical things.

It is, by definition, a duplicate. @Rukachan

**Comment by Rukachan** [comment] 2016-04-02 22:07
@danpantry 
Not in the context of issues. Duplicate(s) are the issues after the first one.

But talking about the word itself, this is the "original", a duplicate is something copying from it. An original by definition can **not** be a duplicate.

http://dictionary.cambridge.org/dictionary/english/duplicate
> something that is an ​exact ​copy of something ​else
> _I ​lost the ​original ​form so they ​sent me a duplicate._
> being an ​exact ​copy of something
> _The ​application has to be ​completed in duplicate._

http://www.thefreedictionary.com/duplicate
> 1. Identically copied from an original.

**Comment by flovilmart** [comment] 2016-04-02 22:18
Should I reopen that one then? Not sure what to do...

**Comment by Rukachan** [comment] 2016-04-02 22:25
I think that just editing your post above where you said "Closing as duplicate" to explain the actual reason you made the new thread would be enough.

**Comment by flovilmart** [comment] 2016-04-02 22:28
I believe that should do?

**Comment by niklas** [comment] 2016-04-03 00:21
Hi. Could you be so kind an remove @tenshihan 's personal info, posted by @lasse-skogland? Doxxing is a detestable action to anyone, no matter how rude one thinks the target was.

Thank you very much.

**Comment by LasseSkogland** [comment] 2016-04-03 00:25
@niklas Especially considering it is my personal information not @tenshihan.

**Comment by flovilmart** [comment] 2016-04-03 01:01
Done.

**Comment by LasseSkogland** [comment] 2016-04-03 01:03
@flovilmart Thank you :)
