### ISSUE TITLE
`request.user` on cloud code is `undefined` with iOS 10

### ISSUE THREAD

**Issue by mohdabdurraafay** [ParsePlatform/parse-server#2783] opened 2016-09-26 11:29 UTC
**Issue Description**

We just updated our iOS codebase to iOS 10 as base SDK with Xcode 8 with Parse iOS SDK version '1.14.2' and Server version 2.2.17. We observed that the cloud functions aren't having the `user` object in the `request` payload on the server which is being made by the iOS 10 compatible app. 

**Steps to reproduce**

- Update your Mac with the latest Xcode 8.
- Then update iOS app codebase to Swift 2.3.
- If your Parse SDK isn't 1.14.2, then please update that as well.
- Now run the app and see your cloud functions on the server has `user` object missing.

**Expected Results**

These cloud functions should have the original payload with the user objects invoke in them.

**Actual Outcome**

There's no `user` object in the request payload.

**Environment Setup**

_Server_

parse-server version (Be specific! Don't say 'latest'.) : v2.2.17
Operating System: Heroku (cedar)
Hardware: Heroku
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroic
Database

MongoDB version:  3.0.12 (MMAPv1)
Storage engine: MMAPv1
Hardware: mLab
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Logs/Trace**

You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by flovilmart** [comment] 2016-09-26 12:18
Can you please provide the logs when running with VERBOSE=1 for those users that are missing?

**Comment by flovilmart** [comment] 2016-09-26 12:25
Also did you try the suggested resolution here: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/437#issuecomment-249507436

**Comment by hramos** [comment] 2016-09-26 19:40
Closing as dupe of #2753.

**Closed by hramos** 2016-09-26 19:40 UTC
