### ISSUE TITLE
Parse.Query.find returns an array of an array of objects in Parse server

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/parse-server#593] opened 2016-02-23 06:10 UTC
On the hosted parse app, "find" gives me an array of objects in the cloud code. I copied the same cloud code to a locally hosted parse server, and it failed to produce the same response on the same data set. After looking into it I found that the response is now an array, first element of which is the response I get on the hosted app. 

Hosted app response:
[{obj1}, {obj2}, {obj3}]

Local parse server response:
[[{obj1}, {obj2}, {obj3}]]

Does this mean that I need to change the way I handle query response EVERYWHERE?

Thanks

**Comment by gfosco** [comment] 2016-02-23 06:43
Can you provide the code/query that you're using?  That doesn't sound right.

**Comment by mmahmood** [comment] 2016-02-23 07:37
The query is used to back a grid with pagination and returns records for that page.

Here's the query being used . I have simplified the query by removing conditions based on filters applied on the grid. Assuming no filters:

exports.getContributionsList = function(user, doofl){
  var query = new Parse.Query("Contribution");
  query.equalTo("doofl", doofl);
  query.equalTo("donor", user);
  return Parse.Promise.when([query.find()])
	*.then(function(contributionsList){*
		*for(i = 0; i < contributionsList.length; i++){*
			var contribution = contributionsList[i];
			var item = { // get required information from the contribution and create a JSON item
			}
			list.push(item);
		}
		return Parse.Promise.as(list);
	}, function(error){
		return Parse.Promise.error(error);
	});
}

This is called using Parse.Promise.when([contributionsJS.getContributionsList(user, doofl)]). 
This was throwing errors on my local parse server when creating the JSON from contribution item, whereas it is working fine on my test Parse instance. Data set and queries being tested are exactly the same. When I logged the contributionsList on console, I saw the difference. The data was [[{obj1},{obj2},{obj3}]]. 

I modified the code to handle this as follows, and it's working fine now:
	*.then(function(contributionsListArr){*
                *var contributionsList = contributionsListArr[0];*
		*for(i = 0; i < contributionsList.length; i++){*

The grid was on a web page backed by express on Parse hosted app. On the Parse server, I have removed the endpoints from /cloud/app.js to parse-server-example/index.js.

**Comment by flovilmart** [comment] 2016-02-23 18:27
@mmahmood this is because you're using `Parse.Promise.when([query.find()]);`

When you pass an array to Parse.Promise.when, the promise will be resolved with an array containing the results from the promises in the order you passed the promises.

you can change to 

 `Parse.Promise.when(query.find()).then(function(results) { }` 

Or

`query.find().then(function(results) {})`

OR

```
Parse.Promise.when([query.find()]).then(function(promisesResults) {
   var queryResults = promisesResults[0];
   ...
}):
```

**Comment by mmahmood** [comment] 2016-02-24 05:43
I understand what you are saying. But in case of the app hosted on Parse, the response is the 1st item of the resulting array even when I pass an array to Parse.Promise.when. I am using this throughout my cloud code and my web app. I get the same result in _list_ in the both the cases below.

_Parse.Promise.when([query.find(), query.count()]).then(function(list, total) {... }
Parse.Promise.when([query.find()]).then(function(list) {... }_

However, this is **not ** the case in **Parse server**. So what you're saying is that I need to change this throughout my code now for it to run on Parse server. Is this correct?

**Comment by drew-gross** [comment] 2016-02-24 06:10
Yes, that is correct. This behaviour changed in version 1.7.0 of the Parse JS SDK (https://github.com/ParsePlatform/Parse-SDK-JS/releases/tag/v1.7.0), which is the one that Parse Server uses. Depending on your specific use case, you may find it easier to change your input to `when` to be arguments, like this:

```
Parse.Promise.then(query.find(), query.count()).then(function(list, total) {})
```

Which should work.

**Closed by drew-gross** 2016-02-24 06:10 UTC
Labels: troubleshooting

**Comment by mmahmood** [comment] 2016-02-24 06:42
Got it. Thanks!

**Comment by mmahmood** [comment] 2016-03-02 17:44
I keep getting "script error" (without any details) when I try to change version from 1.6.14 to 1.7.0. Any pointers as to what I can do?

**Comment by drew-gross** [comment] 2016-03-03 01:03
Can you open a new issue with steps for reproducing the issue on either this repo or the JS SDK repo?
