### ISSUE TITLE
Newbie-friendly docs

### ISSUE THREAD

**Issue by jcano** [ParsePlatform/parse-server#2027] opened 2016-06-10 15:26 UTC
The current docs are either incomplete or written for someone who is familiar with the platform, possibly because there is pressure to get people migrating from parse.com to a self-hosted parse-server.

The docs for the different SDKs are very detailed and mostly valid, except for a few outdated things like the iOS security section describing the old dashboard. But there are a few things that need to be addressed about parse-server when starting from scratch.

In addition to a feature list and other nice things that would help people  understand what Parse is, I think the most important thing is to explain how Parse works. Without using parse-dashboard, for example, I would not know anything about CLP and ACL.

Generally, my feeling is that the documentation for what the server does and how it works is scattered across the docs for all the other elements of the Parse ecosystem (SDKs, dashboard, modules). Without reading the other guides it's almost impossible to understand  what parse-server does and how to use it.

**Comment by hramos** [comment] 2016-06-10 17:32
We're still working with people who are migrating their existing apps which is why our priority has been on migrations, but we still plan to launch an updated docs site aimed at people new to Parse Server. The site is almost done, just need to remove any Parse.com specifics as you mentioned.

CLPs and ACLs are documented in the Parse.com guides under Security in almost every SDK guide. Were you looking for something different in terms of content there?

**Comment by jcano** [comment] 2016-06-10 18:45
Basically all the information is there, but how it is structured is a bit confusing. I spent the last couple of days going through the documentation for the server, dashboard and a few SDKs and in the end is all there.

When I was reading about the server, I was expecting to see the core ideas and principles behind it, like for example the ACL and CLP. Things that might affect how I configure or deploy the server. There are many concepts that are common to all SDKs and should be discussed independently of the SDK. Another example is the "Client Push Enabled" setting, that is a server side config value but is explained on the REST API docs while it also affects the usage of client key and Javascript key.

I'm not 100% familiar with Parse, yet, but it would be easier to get into Parse if some core concepts are explained independently of the platform you will be using them from. In the end, all SDKs offer the same functionality and access the same data so why not explain that in the context of the server (what it is, how it works and its configuration) before going into details about how to implement it?

**Comment by hramos** [comment] 2016-06-10 18:54
Unifying all the docs is one of the main goals of the new docs site. Right now, we have docs spread out over Parse.com (SDK guides plus general Security, Performance, etc guides that may or may not apply to Parse Server) as well as here in the GitHub repository (README covers initial setup, wiki covers usage and development).

**Comment by sprabs** [comment] 2016-06-15 20:34
@hramos are there any docs for REST API with the new parse-server migration? I'm facing some issues when pointing to my own API endpoint (hosted on AWS Elastic Beanstalk) for processes that worked just fine running through parse.com...

I filed an issue here, but haven't gotten any responses yet: https://github.com/ParsePlatform/parse-server/issues/2061

**Comment by hramos** [comment] 2016-06-16 16:07
@sprabs we don't have those docs ready yet. You should be able to use the [Parse.com REST API docs](https://parse.com/docs/rest) for reference, as Parse Server should have the same API surface. There will be a few exceptions, of course, for features that have not been ported to Parse Server. Feel free to open any issues in this repo for things that behave differently and in an unexpected way, and issues in the docs repo for anything that should be updated for the REST API docs in Parse Server. That way we'll make sure to tackle them when the new site goes up.

**Comment by sprabs** [comment] 2016-06-16 17:49
@hramos I did file an issue several days ago. It's a MAJOR problem we are facing through the REST API. Seems to be a difference between parse.com and the parse-server, but no one is verifying/suggesting a workaround. Here's a link to the issue I have filed: https://github.com/ParsePlatform/parse-server/issues/2061

**Comment by hramos** [comment] 2016-06-16 18:31
That actually falls out of scope of what I mean by differences between the REST API in Parse.com and Parse Server, as it appears to be specificly about a performance regression.

**Comment by sprabs** [comment] 2016-06-16 18:38
@hramos Trying to get a process that at most puts a 3 RPS load on the server to work with disrupting everything is a fundamental issue, not a performance regression. I noticed you pinged the other issue. Will comment more there. Thank you for following up.

**Comment by hramos** [comment] 2016-06-16 19:23
Either way, this type of issue is not one of a difference in the REST API surface of a Parse.com vs a Parse Server app, which is what we would need to document in the REST API docs.

**Comment by hramos** [comment] 2016-07-27 22:06
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.

**Closed by hramos** 2016-07-27 22:06 UTC

**Comment by wkwyatt** [comment] 2016-08-15 17:09
I know that this issue has been closed but I have a question about the URL to use when accessing a AWS EB Parse Server with the REST API documentation.  I am currently using "https://api.parse.com/1/classes" right now but it doesn't recognize the cloud code I have added to the parse aws server
