### ISSUE TITLE
Application error Parse Server 2.1.6 Heroku

### ISSUE THREAD

**Issue by nickjf89** [ParsePlatform/parse-server#1076] opened 2016-03-17 11:48 UTC
I have an instance of Parse-Server-Example running on Heroku, which used to work perfectly.

I updated my package.json to support the latest Parse Server version, 2.1.6 (should I be doing this?), and now I get an "Application Error" error on my server.

I'm pretty new to all the Node.js stuff, so can anyone help me resolve this and give me tips for keeping my server up to date in the future?

Thanks

**Comment by davimacedo** [comment] 2016-03-17 20:45
Do you have more details about the error?

**Comment by AmbroiseCollon** [comment] 2016-03-18 09:18
Sorry I was too quick to ask for help on this one. The problem is solved. Thank you for the follow up and my apologies for wasting your time.

**Comment by hramos** [comment] 2016-03-18 21:52
Are @nickjf89 and @AmbroiseCollon the same person? Can we close this issue?

**Comment by nickjf89** [comment] 2016-03-18 21:53
No we are not. But yes please close.

**Closed** 2016-03-18 23:05 UTC
