### ISSUE TITLE
Disable logging in cloud-code

### ISSUE THREAD

**Issue by DrBeak1** [ParsePlatform/parse-server#2518] opened 2016-08-14 17:08 UTC
I just updated to 2.2.17; OMG - how do i disable logging in cloud code? Sorry if this has been answered somewhere else, I looked around and couldn't find anything.

I've tried changing the logLevel at app start:
```
// app.js
var logger = require('parse-server').logger;
logger.logLevel = process.env.PARSE_SERVER_LOG_LEVEL || 'error';
```
... but that doesn't seem to impact cloud code

Thanks in advance.

**Comment by acinader** [comment] 2016-08-15 17:22
well, by my testing, you're right.  I can't set the log level either on master or 2.2.17.  Working on a unit test now to verify and then i'll fix.

**Comment by acinader** [comment] 2016-08-15 19:10
I reproduced the issue on 2.2.17 as follows:

- created a new dir, npm init
- copied over my cloud code
- added minimal dependencies:
``` 
"dependencies": {
    "eslint": "^3.3.0",
    "moment": "^2.14.1",
    "parse-image": "^0.2.0",
    "parse-server": "^2.2.17",
    "parse-server-s3-adapter": "^1.0.4",
    "twilio": "^2.9.2",
    "underscore": "^1.8.3"
  }
```
- created minimal index.js:
```
const express = require('express');
const ParseServer = require('parse-server').ParseServer;
const S3Adapter = require('parse-server-s3-adapter');

const parseServerOptions = {
  logLevel: 'warn',
  appId: 'XXXX',
  masterKey: 'XXX',
  databaseURI: 'XXX',
  serverURL: 'http://localhost:9091/parse',
  port: 9091,
  cloud: './cloud/main.js',
  fileKey: 'XXXX,
  filesAdapter: new S3Adapter({
    bucket: 'XXX',
    bucketPrefix: 'files-dev/',
    directAccess: true,
    baseUrl: 'XXX,
    globalCacheControl: 'public, max-age=31536000',
  }),
};

const app = express();
const api = new ParseServer(parseServerOptions);
const port = 9091;

app.use('/parse', api);

app.listen(port, () => {
  console.log('listening on ' + port);
});

module.exports = app;
```
- then I start the server with: 
```
PARSE_SERVER_LOG_LEVEL=warn S3_ACCESS_KEY=$AWS_ACCESS_KEY_ID S3_SECRET_KEY=$AWS_SECRET_ACCESS_KEY nodemon index.js
```
Note that I am double setting warning: both in the config obj and on the command line.

I then hit it with our app and it works just fine, but I am getting info logs.

I tried to get a unit test to fail on master, but it works.  Here's the unit test:

https://github.com/acinader/parse-server/commit/ec3c5d82697b3b5391153e86e1b16ccfb5d8018e

I'm going to checkout the behavior on master since the big logging refactor.

**Comment by acinader** [comment] 2016-08-15 20:10
on master, setting to warn for neither the logLevel option or PARSE_SERVER_LOG_LEVEL works for me.  Again, my unit tests works, but in the actual server it doesn't.  Will investigate further.

**Comment by acinader** [comment] 2016-08-15 21:44
@flovilmart can you help me out a bit here?

https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Logger/WinstonLogger.js#L49-L54

I'm not sure what the configureLogger declaration is doing...

``` 
function configureLogger({
  logsFolder = defaults.logsFolder,
  jsonLogs = defaults.jsonLogs,
  logLevel = winston.level,
  verbose = defaults.verbose,
  silent = defaults.silent } = {})
```
I added some debugging like so:

```
export function configureLogger({
  logsFolder = defaults.logsFolder,
  jsonLogs = defaults.jsonLogs,
  logLevel = winston.level,
  verbose = defaults.verbose,
  silent = defaults.silent } = {}) {

  console.log(arguments);
  if (verbose) {
    logLevel = 'verbose';
  }
  console.log(logLevel);
  winston.level = logLevel;
  const options = {};
....
```
which gave me this, unexpected output:
```
{ '0': [ { json: true, logLevel: 'warn' } ] }
info
```
I expected that the notation in the function declaration was setting default values?  but now I am just not sure what its purpose is....and more to the point, I am not sure how to send in a log level....

I'm passing logLevel: warn as part of the parse-server constructor object, and I'm also passing it in as part of the LoggerAdapter options object which is the one that is appearing in the arguments to configureLogger.

I'm looking here to try and figure it out...https://babeljs.io/docs/learn-es2015/

**Comment by acinader** [comment] 2016-08-15 22:04
from playing around with the unit test and my setup of parse-server, it looks like the logger level is getting configured before the parser server options....

in my entry point, I am configuring parse-server like this:
```
const express = require('express');
const conf = require('config');
const ParseServer = require('parse-server').ParseServer;
const api = new ParseServer(conf.parseServerOptions);
// Have to instantiate parse before getting the logger.
const logger = require('parse-server').logger;
```
with some debug statements, it look like when i call:
```
const ParseServer = require('parse-server').ParseServer;
```
the logger is getting configured.
when i then instantiate it on the next line, even though my options have ```logLevel: warn``` the logger is not getting reconfigured....
not sure how to replicate that in a unit test so I could start trying to attack the problem....

**Comment by acinader** [comment] 2016-08-15 22:05
oh and the ``PARSE_SERVER_LOG_LEVEL=warn node index.js`` isn't working either... :)

**Comment by acinader** [comment] 2016-08-15 22:17
ok, it looks like the problem is because of my subclass of winston logger.  continuing to investigate....

**Comment by DrBeak1** [comment] 2016-08-16 03:51
@acinader thanks so much for digging into this. So:
```
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev',
  cloud: '/home/myApp/cloud/main.js',
  appId: 'myAppId',
  masterKey: 'myMasterKey',
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse',
  logLevel: 'error' <====== set level here?
});
```
... should work?

**Comment by acinader** [comment] 2016-08-16 16:05
@DrBeak1, futzed a little more.  this will turn it off in 2.2.17 (some things to note at the bottom...):

```
const express = require('express');
const ParseServer = require('parse-server').ParseServer;
const S3Adapter = require('parse-server-s3-adapter');
const configureLogger = require('parse-server/lib/logger').configureLogger;
const logger = require('parse-server').logger;

// Note that I am not using the same port as you!!!
const port = 9091;

const parseServerOptions = {
  appId: 'xxx',
  masterKey: 'xxx',
  databaseURI: 'xxx',
  serverURL: 'http://localhost:9091/parse',
  port: port,
  cloud: './cloud/main.js',
  fileKey: 'xxxx',
  filesAdapter: new S3Adapter({
    bucket: 'xxx',
    bucketPrefix: 'xxx/',
    directAccess: true,
    baseUrl: 'https://xxx',
    globalCacheControl: 'public, max-age=31536000',
  })
};

const app = express();
const api = new ParseServer(parseServerOptions);

configureLogger({ level: 'warn' });

app.use('/parse', api);

app.listen(port, () => {
  logger.info('info');
  logger.warn('warn');
  logger.warn('listening on ' + port);

});

module.exports = app;
```

1. I didn't check what this does to the other options for the logger, so these are the other options you *MAY* need to add your values for  ``logsFolder`` and  ``jsonLogs``
1. keep an eye out for when the next version bump of parse-server comes out and then you'll be able to set like you did above.
1. keep an eye on #2501. I intend to work on this today with the goal to get the logging as close to what was on parse.com at which point you may want to switch back to `info` from `warn`.

And finally, if this answers your question, close the issue?

**Comment by DrBeak1** [comment] 2016-08-17 15:21
Thanks again, @acinader -- I'll give this a shot tonight and report back.

**Comment by DrBeak1** [comment] 2016-08-18 07:24
@acinader I can confirm that your last suggestion **does** in fact work. Thank you, sir!

**Closed** 2016-08-18 07:24 UTC
