### ISSUE TITLE
Android device still receives push from old installationId after app re-install

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/parse-server#1705] opened 2016-05-05 03:57 UTC
1. install the app on Android phone, signup a new user A in Parse, get installationId_1
2. uninstall the app and re-install the app on the same phone, login into the previously created user A, get installationId_2

note that the app on this phone is now associated with installationId_2

now from parse server cloud code, send push notification targeting installationId_1, the app still receives the push even when its installationId is not installationId_1.

**Comment by xor22h** [comment] 2016-05-06 11:08
Probably both installationsId's have the same GCMToken as it's still the same phone. GCMToken is provided by google play services library which you are not reinstalling, so it may return the same GCMToken. So even if you target installation_1, all other installations which includes same GCMToken will still receive the same notification;

**Comment by jiawenzhang** [comment] 2016-05-08 14:43
@xor22h the "deviceToken" for the two installations are different. I believe the "deviceToken" is the GCMToken.

**Comment by flovilmart** [comment] 2016-06-05 17:15
I'm closing this here for now, please update parse-server to the latest version. If the issue is still here, please open on [parse-server-push-adapter](https://github.com/parse-server-modules/parse-server-push-adapter/issues/new).

**Closed by flovilmart** 2016-06-05 17:15 UTC

**Comment by macmoe** [comment] 2016-09-30 22:38
I'm experiencing the same issue and have created https://github.com/parse-server-modules/parse-server-push-adapter/issues/40
