### ISSUE TITLE
Can the parse server  provide services for many apps?

### ISSUE THREAD

**Issue by GongChen1107** [ParsePlatform/parse-server#1722] opened 2016-05-08 13:20 UTC
I have many apps and I am going to migrate they to self host parse-server .I wonder if I can provide services to several  apps by setting up a single machine.I find it seems that cloud code can only for one app.Does the parser server design for supporting only one app.How can I complete the migration of my 100 apps.

**Comment by bohemima** [comment] 2016-05-08 13:35
Currently you will have to run one parse-server per app, they can theoretically all run on the same machine. I would simply let them be terminated by a single nginx and route to different backends based on path or header.

**Comment by GongChen1107** [comment] 2016-05-09 02:05
Yes ,I am using this way to provide different backends of apps.Does the Cloud Code works too ?I find that Cloud Code serverUrl is route to the only one path.Cloud Code function can't map to the correct parse-server.Should I need to set sereverUrl in the main.js.

**Comment by GongChen1107** [comment] 2016-05-10 12:21
@bohemima I have a question that we have some apps need different route of  cloud code.But I find that if requrie an parse the serverUrl is freeze to the first init one.

**Comment by hramos** [comment] 2016-05-10 18:42
Duplicate of #15

**Closed by hramos** 2016-05-10 18:42 UTC
