### ISSUE TITLE
Invalid link (hotmail emailverification)

### ISSUE THREAD

**Issue by Meersad** [ParsePlatform/parse-server#3388] opened 2017-01-17 10:21 UTC
Have server on verifyUserEmails: true,

After register a new user email gets send out with a verification link.
It works totally fine with every email provider we have tried except hotmail.
When the receiver of this is an hotmail user, upon just opening the mail itself (not clicking the link) the verification progress goes though, and when we do klick link we get invalid link coz of it already been used. 

It seams like Hotmail maybe tries to preload the link and that way it fires the link without the user ever even clicking it?? And when they finally do click link they get the invalid link page instead.

There must be other people that have similar issue? What is the solution for this, do we need to modify parse-server to somehow handle if the link gets triggered twice within a span os seconds?
Any ideas?

Does not look good for end user to get "invalid link" but have verify-email true anyway coz of the preload from hotmail

  - mailgun adapter 
  - parse-server version 2.3.2
  - Localhost or remote server AWS

**Comment by lamff** [comment] 2017-01-24 11:10
Hi,

I had the similar problem. I requested and I have got password reset email with one-time link. It was all invalid!
I made a try to disable the Link preview here: in  the **Options->Layout->Link preview** - uncheck.
![hotmail-en](https://cloud.githubusercontent.com/assets/25320536/22244824/5e2affb6-e22d-11e6-83a8-edd55477abd8.png)
After this I get valid urls!
 I hope it will help you.

**Comment by Meersad** [comment] 2017-01-24 11:24
Yes, but that only is for your own inbox. But i would need a way so it does not preload for anyone. Is that possible? 
Right now i made a image with the link instead, and that seams to help, but then i need to send HTML mail instead of plain text.

**Comment by brandly** [comment] 2017-01-27 19:08
What exactly does the email preview do that causes the link to be invalid?

I'm getting a similar report of an invalid password reset link, but it was sent to a hotmail inbox. I'm guessing hotmail is doing something similar, but I still don't understand.

**Comment by lamff** [comment] 2017-01-30 10:12
I think that the email preview in hotmail open the one-time link in the email. (I suppose it is looking for harmful content.)
Since it is a one-time link, it will be invalid on next view.

**Comment by Meersad** [comment] 2017-01-30 12:15
Yes, hotmail and outlook tries to preview the link and links get used up and the email on parse-server gets verified at the same time. 
The reciver of this mail does not know that coz its happening in the background, so when they klick the link they will come to the page "invalid link" but it already just verified the user in background.

This does not look very good in a safety perspective for the enduser. Getting an invalid link and yet be verified user now.... 
The only way i found so far around this is to send HTML mail(with the link embedded in a button) instead of plain text, that way hotmail/outlook will not try to preview mail.

**Comment by hramos** [comment] 2017-02-10 00:03
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Closed by hramos** 2017-02-10 00:03 UTC

**Comment by sirnacnud** [comment] 2017-02-13 22:56
I had a user report encounter this same issue and they were using a hotmail account as well.

**Comment by littleariel** [comment] 2018-09-04 17:11
Was there an actual fix for this? Seeing some users reporting the same thing and telling them to change their email settings doesn't seem like a viable solution.

**Comment by flovilmart** [comment] 2018-09-04 22:38
There wasn’t. Feel free to investigate one if you feel to.

**Comment by littleariel** [comment] 2018-09-04 22:43
Sounds good, will do. Gathering some user info, and will provide all the info if we confirm and reproduce the issue.
