### ISSUE TITLE
Parse hosting after April 28th - what does "deprioritise" mean?

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-server#1653] opened 2016-04-27 08:02 UTC
Hi

I read that if the Parse DB isn't migrated until the April 28th the parse application gets deprioritised ("We recommend migrating your database by the end of April, but migrating your application logic to Parse Server can wait a few more months. If you have migrated your database by April 28th, we won't deprioritise your application server").

What does "deprioritise your application server" effectively means? Is the request rate capped? DB slow? Get the application shut down before next january?

**Comment by bohemima** [comment] 2016-04-27 08:10
https://github.com/ParsePlatform/parse-server/issues/1639#issuecomment-214713528

**Comment by neophob** [comment] 2016-04-27 08:46
Thanks @bohemima - I saw those comments:

> As I've understood Parse will prioritize migrated instances after this deadline but will not shut anything down. I read it as your QPS performance might take a hit or something similar. I found #1106 (comment) from Drew

> you can keep your app server on Parse.com after you've migrated your database. We recommend migrating your database by the end of April, but migrating your application logic to Parse Server can wait a few more months. If you have migrated your database by April 28th, we won't deprioritise your application server

But I'm still not 100% sure what it means, especially "but migrating your application logic to Parse Server can wait a few more months." - does this means db migration can't wait? What are the concrete impacts?

**Comment by FridaySG** [comment] 2016-04-27 09:16
I think what it means is that simply applications with migrated databases will have resource priority over those without, and would probably only be noticed when Parse is experiencing heavy traffic. I don't think it means they will intentionally slow it down.  I could be wrong though, Parse reps have the final word.

**Comment by drew-gross** [comment] 2016-04-27 18:30
Duplicate of #1106 and https://github.com/ParsePlatform/parse-server/issues/1639#issuecomment-214713528

**Comment by araskin** [comment] 2016-04-27 20:16
So can we have that confirmed from some one at Parse? What does 'reprioritize' mean?

**Comment by hramos** [comment] 2016-04-27 21:16
Closing as duplicate of #1639. See my [comment](https://github.com/ParsePlatform/parse-server/issues/1639#issuecomment-215231644).

**Closed by hramos** 2016-04-27 21:16 UTC
