### ISSUE TITLE
Push Delivery

### ISSUE THREAD

**Issue by bagusflyer** [ParsePlatform/parse-server#5] opened 2016-01-28 23:49 UTC
It's very sad that parse.com will terminate within one year. Some of our applications will be affected. I'm developing an application right now which is using parse.com as backend. Should I re-develop everything or I can just use parse-server in my own server with current source code?

Another question is regarding with push notification. A few of my applications are using Push Notification. Are you going to release the source code for this part in the future? Or we have to develop our own Push Notification system?

Thanks.

**Comment by gfosco** [comment] 2016-01-28 23:51
We'd like to see a push delivery system added to parse-server, whether the community writes it or we do... It's definitely going to happen.  

I can't make the decision for you, but I think with parse-server and the open SDKs, you can continue building on Parse for years to come (just host the server code yourself.)..  

Over the weekend I setup Mongo and parse-server on a $5/month DigitalOcean box to build a quick idea, it was super easy.

**Comment by pfcvik** [comment] 2016-01-28 23:54
It would be very grateful about that tutorial

**Comment by inlined** [comment] 2016-01-28 23:55
@bagusflyer I'm the former tech lead for Parse Push and now work on Firebase/Google Cloud. I'm keen to see that few to none of my former customers get left out in the cold for having put their faith in my product. If you want to go into detail on your use cases, I can try to help you evaluate some migration paths too. My best expertise would be using AWS (what we built Parse on) and Cloud (what I now work with).

FWIW, Parse Push had much more complicated requirements back in the day. Both Apple and Google have improved their push protocols dramatically, so a new service might be easier to build.

**Comment by gfosco** [comment] 2016-01-29 00:01
Developing a push delivery system on parse-server will not be a difficult process.  Luckily, it will only need to support a single app, instead of hundreds of thousands of apps.

**Comment by prodigga** [comment] 2016-01-29 00:10
@inlined @gfosco thanks for responding to questions and being so open about all this.

I recently (a month ago) recommended to my boss that we use Parse as our backend for our mobile games leaderboards and async 'tournament' gameplay mode. Parse was an awesome choice - it let us get started quickly and let us do lots of cool stuff, like checking to see if your new score beat a friends score and sending that friend a push notification if it did - all with cloud code! 

I think the push notifications are a big part of any 'connected' app and it would be great to see a parse push implementation, or at the very least a tutorial/guide to migrate existing device instalations form our parse database to a 3rd party service.

Also, are developing in Unity3D and, unfortunately, Unity3D related features usually get lower priority. I don't see this being much of an issue, since most of these changes are back end stuff. But a few things did catch my eye when skimming over the migration guide - it mentioned in the guide that we should release an update to our app and make sure the app points to the correct server. I'm not even sure if this part of the API is exposed for the Unity version of the Parse client, for example.   

I am rambling here, and just voicing concearns, I guess what I am trying to figure out is if we really would be able to transfer seamlessly across to private hosting (minus push notifications) using the Unity version of Parse.

**Comment by richardjrossiii** [comment] 2016-01-29 00:17
@prodigga Correct, migration for Unity 3D is still in limbo. It's there for the rest of our .NET SDK, but I still need to write the glue code to make ParseInitializeBehavior accept a URL. 

Rest assured it is coming, along with a few other Unity features that have been in the pipe for a while now.

If you wouldn't mind opening an issue for that on the actual .NET SDK repo (https://github.com/parseplatform/parse-sdk-dotNet/issues), we can handle the actual discussion of that there.

**Comment by prodigga** [comment] 2016-01-29 00:28
@richardjrossiii Opened an issue here https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166

**Comment by prodigga** [comment] 2016-01-29 00:35
@gfosco could you go in to some more detail as to how one would go about implementing this? It sounds like you know how you would go about implementing it already, so your insight would be great for other developers.

**Comment by yemaw** [comment] 2016-01-29 02:00
Will Parse team going to actively maintain and develop Parse Server and Parse SDKs after 2017? This is very important for us to make decision whether we should change to another service or host Parse Server our-self.

**Comment by zhouhao27** [comment] 2016-01-29 03:32
@yemaw, I have the same concerns as you have. If Parse SDK will not be actively maintain then we have no point to continue to use it in the future. Maybe we'll take some efforts to migrate to other system or to build our own backend system if that is the case. But I feel the painless solution could be to host **Parse Server** on our own server.

**Comment by bmueller** [comment] 2016-01-29 06:09
@gfosco would really appreciate a push delivery system added to parse-server in the near future. I make heavy use of the subscription channels, so having something provided by your team would make this transition a lot less painful.

**Comment by chavanshashank** [comment] 2016-01-29 07:26
Yeah push delivery is important!

**Comment by silviucpp** [comment] 2016-01-29 08:13
There are any other alternatives to PPNS ? The problem with GCM is that there is no available on all mobile devices. Also you need to have Google Play Services installed which is quite big.  PPNS will be available open source?

**Comment by Telemakhos** [comment] 2016-01-29 09:44
@bmueller [node-gcm](https://github.com/ToothlessGear/node-gcm) allows [subscriptions](https://developers.google.com/cloud-messaging/topic-messaging) and would be fairly easy to implement in this project... It can deliver Apple and Android pushes.

**Comment by erlichmen** [comment] 2016-01-29 10:18
I'm the developer of sambame/open-urban-airship it an open source nodejs server that mimics urban push API and It powers at least three pretty big products out there. It supports sending Android and iOS and it's backup by mongo.
I would love to help integrate that with the Parse platform.

**Comment by TheGhoul21** [comment] 2016-01-29 10:19
we're currently using parse.com for its really nice push notifications. Losing this would be really awful for us, so I'd be pleased to help somehow. What's the plan?

**Comment by guenard** [comment] 2016-01-29 10:50
Believe me.. it won't be easy to add a fast, reliable and open-source push sender to Parse Server (APNS/GCM feedback loop, fast queuing etc.). Developers used Parse instead of a homemade sender for a reason.

Consider switching to a third party like **[Batch.com](https://batch.com)** where you can use Parse's installation id to send transactional notifications. And it comes with a web dashboard obviously.

**Comment by vdharankar** [comment] 2016-01-29 12:44
No definite reply on future maintenance, it worrying, its like use it at your own risk. I am screwed big time as we were nearing to actual product release. Shouldn't have trusted Facebook.

**Comment by luco** [comment] 2016-01-29 12:50
I used push notifications more than anything else. As said, Push is very important.

**Comment by Telemakhos** [comment] 2016-01-29 12:53
@vdharankar the pace of growth in stars of this repo is a clear indicator that the project has legs... it's too early to make predictions and you have a year to switch to your own servers or other alternatives (Firebase, Couchbase, etc)... pretty doable IMO

**Comment by johnrufusj** [comment] 2016-01-29 13:26
@erlichmen interesting...

**Comment by epeli** [comment] 2016-01-29 13:28
Here's one self hosted alternative https://github.com/rs/pushd

**Comment by kingmatusevich** [comment] 2016-01-29 14:36
Push is the main reason I chose parse. Push should be implemented.

**Comment by flessard** [comment] 2016-01-29 14:37
Yeah, Push should be implemented. +1

**Comment by Telemakhos** [comment] 2016-01-29 14:41
@epeli Nice one! pushd looks awesome!

**Comment by kingmatusevich** [comment] 2016-01-29 14:44
Indeed, pushd seems great, Embedding it into the parse server should be easy, the remaining question is configuring the various SDKs to work with it.

**Comment by didierfranc** [comment] 2016-01-29 15:31
Push implementation would be reassuring news

**Comment by alexrmacleod** [comment] 2016-01-29 23:38
@gfosco It's a sad day, I literally felt sick when I heard the news. I came to parse because it made push notifications so simple. I then fell in love with the dashboard and cloud code. It's clear that if these remain, parse will continue to be the leader in mobile dev.

**Comment by kingmatusevich** [comment] 2016-01-29 23:50
These (push and dashboard) have been confirmed in https://github.com/ParsePlatform/parse-server/issues/56, quote:

> I can't guarantee a specific launch date, but rest assured we are at this very moment working on push notifs (for android and ios) and the dashboard.

Also:

> Push probably in the next month, and a lite version of the dashboard within two.

**Comment by bagusflyer** [comment] 2016-01-30 01:19
@kingmatusevich These are good news.

**Comment by silviucpp** [comment] 2016-01-30 06:09
PPNS will still be available ? Or only the wrappers around GCM and APNS ?

**Comment by lacker** [comment] 2016-01-30 06:18
I don't think we should try to cram PPNS in here - it seems like people should just switch to GCM at this point, since recent Android OS's make nonstandard push services a lot worse. Also running a server that holds sockets open is generally way more complex to operate than running a webserver that handles requests.

**Comment by talkaboutdesign** [comment] 2016-02-02 14:21
I migrated my push to One Signal. Really awesome. They even provider a Parse importer.

**Comment by silviucpp** [comment] 2016-02-02 15:08
@lacker I think PPNS is still important and similar services are used inside facebook messenger, watsapp and viber. The reason being that GCM is not reliable and requires to have Google Play services.

**Comment by zhouhao27** [comment] 2016-02-04 05:03
@talkaboutdesign One Signal is great. But worried it may also shutdown someday so that have to find another solution again.

**Comment by gateway** [comment] 2016-02-04 20:22
Sorry guys I'm late to the game but I see some push code being added to the parse server.  I was wondering how this worked before.. Parse Push --> Message Que (RabbitMQ) --> Amazon SNS or did you guys build your own push server, which now thinking of it I think you did because you had to upload the certs to parse.

I'm wondering though on the suggested flow above if this could be implemented.  We used SNS quite a bit in the past and it worked out pretty well and the price is just amazing but we had to build our own notification server that pushed data to a que and out to the wild.

May I suggest a work flow like this

Parse Push that could be trigged by cloud code.. with substitution variables in it "{0} gave you {1} gold" (using a game example).. the variables can be pulled from cloud code query and pushed then into a message que (rabbitMQ, or a service like http://www.iron.io/), when its ready to go out (if its timed or needs to go out immediately) send the info via api request to amazon SNS.

The only issue with using SNS is that it needs to have the device tokens injected, which instead of putting them in installations you can push them into SNS.. or keep them at both locations and have the ability to add/remove from mongo and SNS.. 

You can also create subscriptions to send out mass texts as well .. anyhow just a thought.. 

screenshot of SNS.. 

![image](https://cloud.githubusercontent.com/assets/519563/12828476/ee3a5d74-cb39-11e5-8b35-9be01b8d0969.png)

**Comment by gateway** [comment] 2016-02-05 18:46
btw Amazon is suggestion a solution, its not complete since you still need a server or message que to talk and send out via SNS https://mobile.awsblog.com/post/Tx3NE69QDHI7LJK/Migrating-from-Parse-Push-to-Amazon-SNS

**Comment by anilkbhatt** [comment] 2016-02-09 00:35
We are primarily using parse push and was happy to see that parse team is making the entire server implementation  available as open source. I almost recommended to my team to host the parse server ourselves and migrate to it, but then realized parse push is not yet available as port of the open source.
Our decision on the alternative will be depending on whether parse push will be eventually made available as part of the open source. If not we will need to look at other solutions, but our first preference would be host the parse server ourselves if it will support push notifications.
We primarily want a delivery system to GCM and APN frameworks. We can live without  stand alone parse push (that is ,  we don't need parse's own proprietary push notification mechanism which was used primarily for android devices without Google Play Services).
I hope  parse push t will be supported as part of the open source soon (the part which leverages APN and GCM).

**Comment by rosarioconti** [comment] 2016-02-09 01:01
Open Signal it's an option but seeing that the parse team is adding the code it's much better. 
 Just wondering about one thing, why am I seeing so many bugs ? Wasn't suppose to be open source and work as before? 
 I mean I understand there are different dependencies to take in count but I'm curious about all these changes, that's all.

**Comment by gateway** [comment] 2016-02-09 01:04
@rosarioconti from what I understand Parse Server they use was written in GO and is being ported over to Node.js

**Comment by gfosco** [comment] 2016-02-14 10:15
Closing since Push delivery and push adapters have landed in 2.0.8. :+1:

**Closed by gfosco** 2016-02-14 10:15 UTC
Labels: discussion
