### ISSUE TITLE
Hacked : MongoDB

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/parse-server#3342] opened 2017-01-08 09:02 UTC
MongoDB has been hacked. Data has been destroyed and the attacker is asking for a ransom to get back the data. He has left a collection with this information in the db.

```
{  
   "_id":ObjectId("5871e9419d52c87b58747570"),
   "btcAddress":"18eUPJLM79zdXKYWZSzT29fBQScFwU81VR",
   "email":"0704341626asdf@sigaint.org",
   "note":"Your database has been pwned because it is publically accessible at port 27017 with no authentication (wtf were you thinking?). Your data has been dumped (with data types preserved), and is easily restoreable. To get your data back, email the supplied email after sending 0.15BTC to the supplied Bitcoin wallet, do this quickly as after 72 hours your data will be erased (if an email is not sent by then). We will get back to you within 2 days. All of your data will be restored to you upon payment via a email response. We do admit it is possible we overwrote another groups warning after they hit you. In this case, we will refund you 75% and send you the emails of the other groups. We are not animals. In fact, you should be glad we hit you before some groups did something terrible with your data like sell it online.",
   "alias":"C8_H10_N4_O2"
}
```

How could they access it? My db is password protected?  Could have at least warned before doing this. Getting initial users was such a drag and somebody comes out and does this. 

Check this [Google doc] (https://docs.google.com/spreadsheets/d/1QonE9oeMOQHVh8heFIyeqrjfKEViL0poLnY8mAakKhM/edit#gid=0) for more.

Any tutorial or docs Parse can provide so that we db noobs can secure our data in the future and also is there any way to get the data?

**Comment by natanrolnik** [comment] 2017-01-08 09:09
Closing as duplicate of #3334 and #3330.

Check the links posted in both issues, they might help you.

**Closed by natanrolnik** 2017-01-08 09:09 UTC

**Comment by skinp** [comment] 2017-01-08 23:41
One thought I had about the data, maybe the hackers didn't drop the oplog? If it's the case, you might be able to get *some* data back. Have a look in local.oplog.rs...
Even if the oplog hasn't been cleared, it won't be easy to recover from it (it's pretty technical and I can't help with that) but at least it's something that might be useful...
