### ISSUE TITLE
ERR! parse-server-push-adapter APNS cannot find vaild connection

### ISSUE THREAD

**Issue by funkenstrahlen** [ParsePlatform/parse-server#1665] opened 2016-04-28 08:31 UTC
My parse server log is filled with `ERR! parse-server-push-adapter APNS cannot find vaild connection` errors. Push Notifications reach devices though. This seems to happen for devices that uninstalled the app and are now no longer reachable.

- [X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

```js
    push: {
        android: { senderId: '...', apiKey: '...' }, // setting android keys empty to remove error
        ios: {
          pfx: __dirname + process.env.APN_PUSH_P12_PATH, // The filename of private key and certificate in PFX or PKCS12 format from disk  
          bundleId: process.env.APN_BUNDLE_ID, // The bundle identifier associate with your app
          production: false // Specifies which environment to connect to: Production
        }
    }
```

#### Steps to reproduce

* Install app on device. Does register to parse server
* Uninstall app
* send push notification

#### Expected Behaviour

Devices that are no longer reachable get removed from the database.

#### Logs/Trace

```
Apr 19 20:36:36 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 19 20:36:36 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 19 20:36:37 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 19 21:42:54 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 19 21:42:55 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 19 21:42:55 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 20 19:29:50 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 20 19:29:51 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 20 19:29:52 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 20 23:56:00 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 20 23:56:01 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 20 23:56:02 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 21 20:30:10 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 21 20:30:11 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 21 20:30:12 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 21 22:30:59 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 21 22:31:00 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 21 22:31:01 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 22 16:17:58 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 22 16:17:58 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 22 16:17:59 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 22 16:33:06 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 22 16:33:07 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 22 16:33:07 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 22 16:34:49 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 22 16:34:50 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 22 16:34:51 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 22 17:10:04 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 22 17:10:04 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 22 17:10:05 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 24 10:47:19 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 24 10:47:19 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 24 10:47:20 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 24 11:02:55 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 24 11:02:56 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 24 11:02:57 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 24 11:25:33 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 24 11:25:34 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 24 11:25:34 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
Apr 24 11:38:18 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 03750761765ab097c58b1f90d30a078d892
Apr 24 11:38:18 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 37bc6500dd5e33ff43dc7a3f1e45ebc25a5
Apr 24 11:38:19 xsn-app parse-app-production[6721]: ERR! parse-server-push-adapter APNS cannot find vaild connection for 899efce347b266412d39da18379569bdaa7
```

**Comment by YuanForWork** [comment] 2016-04-28 23:35
Meet the same problem.

Anybody have solutions for that?

**Comment by flessard** [comment] 2016-04-30 00:01
Same problem here !

**Comment by flessard** [comment] 2016-04-30 11:46
I fix the problem by removing 

`production: false `

If this line is present, i got "APNS cannot find vaild connection" whatever if i set `true` or `false` 

Strange!!!!

**Comment by florianthompson** [comment] 2016-05-08 10:45
Did you fix the problem? 
Otherwise I would try to put the bundle identifier in quotes like: bundleId: 'process.env.APN_BUNDLE_ID':
I hope it helps

**Comment by funkenstrahlen** [comment] 2016-05-17 14:51
The problem is still present. I did not try setting `production: false` as this is happening in my production environment.

The make it clear: **Push notification do get send out fine**. I just do not know why this error appears. I *think* the error is caused by devices which do not have the app installed any more?

**Comment by flovilmart** [comment] 2016-06-05 17:13
@funkenstrahlen that may be possible. I'm closing this issue here for now, it is still problematic please reopen on [parse-server-push-adapter](https://github.com/parse-server-modules/parse-server-push-adapter/issues/new).

**Closed by flovilmart** 2016-06-05 17:13 UTC

**Comment by KevinLaity** [comment] 2016-10-24 17:09
I found that (as flessard notes above) if I don't specify "production" at all, push notifications start working with either dev or production certificate. 

Maybe it's meant only to be used if you're specifying an array of certificates?

The problem is that examples [like the one here](https://github.com/ParsePlatform/parse-server/wiki/Push#user-content-2-configure-parse-server) ask you to include it regardless!
