### ISSUE TITLE
Migration to external mongo db does not populate file data 

### ISSUE THREAD

**Issue by ndnguru** [ParsePlatform/parse-server#434] opened 2016-02-15 21:45 UTC
When I tried the migration tool to (transferring to MongoLab), I ran into an issue with files.  The migration tool doesn't seem to populate the type, url or name of the file object.

Here is my issue:
I started the migration of my data to a mongoLab db.  Then when I went to MonoLab to verify, I noticed a big problem!  On my _User collection, for example, I have a field 'photoFile', which stores an image (jpg, png, etc).  

When I export the data to JSON using Parse's export tool from the data browser on Parse, I see sufficient data about that photoFile field (example below, what I expect to see in the mongo db):

```
{
...
"photoFile": {
            "__type": "File",            
            "name": "tfss-XXX-XXX-ETC.png",
            "url": "http://files.parsetfss.com/asdfasdfasdf/tfss-XXX-XXX-ETC.png"
        }
...
}

```

Now, when I look in the new MongoLab collection for that _User collection, it just has the filename listed instead.  No type or location data (URL) is provided as with the JSON export above:
```
//what I actually see in the mongo db
{
...
     "photoFile": "tfss-XXX-XXX-ETC.png"  
...
}
```

Questions: 
1.  How do I know where to access my data!? No URL means no clue where the file is!
2.  Do I have to change the way I access data on the client side?
3.  How do we migrate files from parse file servers to our own S3 buckets?

**Comment by christianmarth** [comment] 2016-02-16 00:12
Duplicate of #420 and #113

**Comment by gfosco** [comment] 2016-02-16 05:09
So, this is how files have been stored in the database, but the server changes the object before returning it to a client via a query.  By providing parse-server with a fileKey (from the parse dashboard settings,) the server can know how to render the same urls.  Shouldn't lead to any client changes.

An actual S3 -> S3 migration is being planned.  Follow along in #8.  Thanks. :+1:

**Closed by gfosco** 2016-02-16 05:09 UTC
