### ISSUE TITLE
Regression in parse server 2.3.3 getting {"code":209,"message":"invalid session token"} with master key sometimes

### ISSUE THREAD

**Issue by jbpringuey** [ParsePlatform/parse-server#3516] opened 2017-02-15 03:26 UTC
### Issue Description

Version 2.3.3 created lot of production issues for us. It seems that some changes happened around how sessions are managed and users are cached.
One of the big problems is that our jobs started failing with {"code":209,"message":"invalid session token"} even if **we use master key** . Another problem is that one of our public cloud function which also use master key started failing with that same error also.

**Rolling back to 2.3.2 fixes our issues.**

### Steps to reproduce

Write a job or a cloud function which uses masterKey and it will randomly (Have not had the chance yet to find exact steps) to fail.

#### Expected Results

Jobs using Master key in all queries and API should not throw invalid session token

#### Actual Outcome

Jobs using Master key in all queries and API should not throw invalid session token

### Environment Setup

- **Server**
  - parse-server version : 2.3.3
  - Operating System:     Heroku Dyno (Linux I beleive)
  - Localhost or remote server? Heroku

- **Database**
  - MongoDB version: 3.0.11 
  - Storage engine:  MMAPv1
  - Hardware:       40 GB SSD on AWS
  - Localhost or remote server? Heroku

### Logs/Trace

  An error happened during execution of mainJob: {"code":209,"message":"invalid session token"}

**Comment by flovilmart** [comment] 2017-02-15 03:53
We're you by any chance using Parse.Cloud.useMasterKey()?

**Comment by jbpringuey** [comment] 2017-02-15 04:00
@flovilmart no we are using query.find({useMasterKey: true}) all over the code

**Comment by NatanRolnik** [comment] 2017-02-15 08:34
@jbpringuey can you please share part of your code, some logs, or a bit more information?

**Comment by dstarke** [comment] 2017-02-16 01:13
I'm seeing something similar. At some point, a bunch of requests made from cloud code start failing with invalid session token errors. I haven't figured out how to reproduce it yet, but I've been looking at it.

However, in my case, every time I've seen this error so far, it has either included or been preceded by calls to code that calls `fetch()`, `find()`, `first()`, `each()`, or `save()` on publicly readable and writable objects without specifying either a session token or `useMasterKey:true` in the options. That code usually works, and then it seems something happens that makes things start failing.

Clearly there were some issues in the code I'm working on, and I've now fixed all those calls by supplying a session token or master key, but I don't think the behavior of that code should suddenly change in this way. I hope this additional information can help track down the problem.

**Comment by flovilmart** [comment] 2017-02-16 03:34
@jbringuey can you provide code/objects examples that makes those calls fail?

**Comment by jbpringuey** [comment] 2017-02-17 03:08
@flovilmart  I am working on repro steps right now, it may have to do with user caching. I am also seeing the issue now in the prior version but not as frequent so it may be a bug that has always been there.

The only thing that has changed recently on our side is the # of users/sessions which has increased and we are still using local caching instead of redis because the redis implementation would slow us down because it always deserialize from redis and does not cache locally.

here is some sample code which is wrapped around a parse function and sometimes runs into {"code":209,"message":"invalid session token"} : 

             `         var orgQuery = new Parse.Query("CoolrOrganization");
			orgQuery.equalTo("name", userCompanyName);
			return orgQuery.find({useMasterKey: true}).then(function (results) {
				if (results.length > 0) {
					var excludedEmails = results[0].get("excludedEmails");
					if (!_.isUndefined(excludedEmails) && excludedEmails.length > 0) {
						if (_.contains(excludedEmails, email)) {
							response.error("BlackListedEmail");
                                                        return Parse.Promise.error("BlackListedEmail");
						}
					}
				}
				return Parse.Promise.as();
		         });`

**Comment by flovilmart** [comment] 2017-02-17 03:40
With useMasterKey, there should never be a invalidSesssionToken yielded. That's most likely a bug

**Comment by maximeloizeau** [comment] 2017-02-17 11:45
I didn't have time to recreate a proper ticket for the issue I raised a 2 weeks ago. This issue may be related to it #3471

In short, the Parse JS SDK is using the last user token it cached to make a request if no session token is provided.

**Comment by dstarke** [comment] 2017-02-17 20:24
@jbpringuey Are you using LiveQuery? One thing I just noticed is that the LiveQuery code is calling `enableUnsafeCurrentUser()`. This, along to a call to `become(sessionToken)` (which would fail if `unsafeCurrentUser` were disabled) in LiveQuery's session token cache, is (I think) how user information is getting cached when it should not be.

Since the comments in the code, along with the method name, indicate that this method is unsafe on the server, the LiveQuery code should not be doing this.

**Comment by dstarke** [comment] 2017-02-17 23:16
The LiveQuery code also had a call to `Query.find()` that was not issued with the master key. The combination of that with the issue I described above could have been causing these problems. I've created a pull request that fixes these issues.

**Comment by jbpringuey** [comment] 2017-02-19 01:41
@flovilmart @dstarke  I am not using so I am not sure this is a dup of 3525 . @maximeloizeau can you please give more details on what you think this is and point to the code that is causing the issue ? It seems much more like what I am facing. I was planning to do some debugging next week. thanks !

**Comment by flovilmart** [comment] 2017-02-19 01:55
@jbpringuey that would help if you could get the logs with running with VERBOSE=1, so we can make sure what's causing the issue.

**Comment by jbpringuey** [comment] 2017-02-19 04:23
yes @flovilmart I will extract prod VERBOSE  logs next time I see the issue

**Comment by jbpringuey** [comment] 2017-02-19 06:02
The code I pasted above is inside a
`
Parse.Config.get().then(function(config) {
...
});
`
and from looking at my application logs more, everything seems to indicate that there is with the config and not useMasterKey as I was thinking.
I will put the VERBOSE as soon as the issue happens again.

**Comment by maximeloizeau** [comment] 2017-02-19 13:08
I will try to detail my findings, please correct me if I am wrong at any step.

It only happens in a specific case I think, when you use the logIn method in Cloud Code. Reproduction:
- User logs in by calling a Cloud Code function that will call the Parse.User.logIn method
  This method will set the current user in cache, [see here](https://github.com/ParsePlatform/Parse-SDK-JS/blob/2956decbe54f2cf6d2c17ff1b4d8db98327410d6/src/ParseUser.js#L941)
- _everything works as normal_
- this user logs out through the Parse.User.logOut on client side (iOS in this case)
   Parse-server responds to the /logout request and delete the related _Session object, [see here](https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/UsersRouter.js#L175)
- a request is made without session token to a Cloud Code function. In this function, we make a Parse.Query.
    -- since there is no session token provided, the RESTController will try to get the current user, [see here](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/RESTController.js#L206)
    -- it will find the user above because it was save as currentUser in the first step

**The query returns _invalid session token_ because the _Session doesn't exist anymore**


One solution I first thought would be to call logOut in Cloud Code, but if you have multiple server instances, it would not work.


So after reading this thread, I think this can be fixed the same way @dstarke did, but we will need to make sure the static method Parse.User.currentAsync() is called instead of Parse.User.currentUserAsync() (not sure if that's that easy)


I really hope this is clear and can help.

**Comment by flovilmart** [comment] 2017-02-19 13:44
You should not in one way or another 'login' the user server side. when needing to impersonate a user, you need to pass the sessionToken to your calls

**Comment by maximeloizeau** [comment] 2017-02-19 14:37
We are not using logIn for that, to make queries we always use the sessionToken. We use it for a phone number based logIn so the user never really logs in with his password but through an SMS (I think the code is based on that [article](https://www.twilio.com/blog/2015/07/build-easy-phone-number-based-login-with-twilio-and-parse.html))

The logIn method allows us to create the session and return it to the user.

**Comment by jbpringuey** [comment] 2017-02-20 16:53
Update on this issue @flovilmart .I am 99 % sure that the problem is with 
` Parse.Config.get().then(function (config) {...}` . 
I started seeing the problem again this morning but when I turned VERBOSE, it went away because the nodes restarted ....

I am running on heroku with 5 dynos and I am not using REDIS. I have observed that when the problem happened this morning, it was only with requests trying to get the config on web.1 . Request going to web.2, web.3 etc... were ok.

I am going to try to repro this morning locally by trying to put a lot of data in the local cache. I am also planning to switch to REDIS in prod to see if that fixes the issue.

let me know what you think.

See jobs started failing randomly : 

![image](https://cloud.githubusercontent.com/assets/251117/23134266/fd946738-f748-11e6-9e67-6a84621ea32e.png)


See error in the logs : 
![image](https://cloud.githubusercontent.com/assets/251117/23134320/326045ae-f749-11e6-91a8-12fb8f9fd92a.png)

Code that is failing : 
`console.log("userCompanyName : "+userCompanyName);
  Parse.Config.get().then(function (config) {
        console.log('sendVerification : getting configurations ');
       ....
  });
  `
as you can see in the logs "sendVerification : getting configurations" is not there.

**Comment by flovilmart** [comment] 2017-02-20 16:55
Uhm, so there is basically a sessionToken that gets sent alongside your Parse.Config.get(), from cloud code, which is invalid. I'm really curious where that session token comes from. Can you update to 2.3.5, and see how it goes?

**Comment by dstarke** [comment] 2017-02-20 20:25
I think that, in theory, you should be able to call `logIn` on the server, as long as you haven't called `enableUnsafeCurrentUser()`. When `unsafeCurrentUser` is disabled, it looks like all the code I can find that might set the current user in the cache is skipped, and that's clearly the intent of the code. (If you do this, you'll need to use the resulting user directly, and not rely on there being a current user, since there shouldn't be one.)

Not all the code that _uses_ the current user is skipped when `unsafeCurrentUser` is disabled, however, which means that if somehow a user gets stored into the current user cache, the client will start sending its token to the server on every call. (This includes calls made with the master key, which I think is another bug in the JS SDK. As far as I can tell, though, the server correctly ignores the session token if the request also includes a master key. This means you can make any individual call not fail by calling it with `useMasterKey:true`, including `Config.get()`, but this doesn't resolve the underlying problem, it just pushes it off to potentially fail somewhere else.)

There were a couple of other things I noticed in the JS SDK's User implementation. There are some inconsistencies where Parse.User's static methods behave differently than the equivalent methods on the default User Controller (the static methods check if `unsafeCurrentUser` is disabled and return nil or throw errors, while the default User Controller ones don't). In addition, ParseUser's `setCurrentUser()` should probably throw an error when `unsafeCurrentUser` is disabled. I don't think any of these are the root cause here, though fixing them could guard against the problem.

The question I have is how a value is getting saved into the current user cache in a node environment? This must be happening at some point before the call that is failing. Possibly a long time before, since things will continue to work correctly until the cached session token becomes invalid.

The only place I could find that was potentially doing that was in the LiveQuery code, which has now been fixed in 2.3.5. One possibility for tracking this down further if it's still happening would be to instrument a version of Parse.User in the JS SDK to log anywhere where the cached current user is set, which should never happen on the server.

**Comment by jbpringuey** [comment] 2017-02-20 20:54
I think that @dstarke  has a good point. I have just noticed that we added recently a Parse.User.become(token) in our of our cloud function and if that one user logs out, it seem to be causing a problem with parse config get. I am planning to debug that a little later. For the time being I am removing that call to see if we stop having all those problem in production.

**Comment by jbpringuey** [comment] 2017-02-20 21:31
@flovilmart I was thinking to add a validation to throw an error anytime someone uses methods like Parse.User.become(token) on the server side. I agree with you that logging in on the server side is not allowed yet I was doing it somehow. By removing Parse.User.become, the issue seems to be gone after multiple attempts.

**Comment by dstarke** [comment] 2017-02-20 21:37
`Parse.User.become()` should already throw an error when used on the server, unless you have explicitly called `enableUnsafeCurrentUser()`, which you should not do.

**Comment by jbpringuey** [comment] 2017-02-20 21:50
@dstarke I am not calling enableUnsafeCurrentUser anywhere in my parse server code

**Comment by flovilmart** [comment] 2017-02-20 22:30
For some reasons liveQuery was enabling unsafeCurrentUser on the server. Which should be fixed as of 2.3.5

**Comment by jbpringuey** [comment] 2017-02-21 15:51
ok I think we can close this issue then. After removing the call to  `Parse.User.become()` we are not seeing the issue anymore. Thanks all !

**Closed** 2017-02-21 15:51 UTC

**Comment by flovilmart** [comment] 2017-02-21 16:07
Good to hear we have a proper conclusion.
