### ISSUE TITLE
Timeout after two weeks

### ISSUE THREAD

**Issue by carrascoacd** [ParsePlatform/parse-server#2577] opened 2016-08-24 11:32 UTC
After installing parse as node.js app (with other api services) over Docker, the server is working as expected but after two weeks of life Parse gets frozen and I need to restart the container in order to get back Parse.

The server is working because other requests are working but not the Parse api that takes too long and produces timeouts.

Thank you.

**Comment by flovilmart** [comment] 2016-08-24 12:09
Is the memory / CPU ramping up before the freeze? Is the performance degrading?

**Comment by mutex007** [comment] 2016-08-28 09:56
We are running multiple parse server deployments as well and this is also a problem for [**some**] of our clients. Memory and CPU is stable but the issue happens randomly. It could be as little as 30 mins, 1 Week or even months. All other routes will work but until a restart of the the container, the parse api will continue to timeout. This problem has persisted for a while now going back as far back as May.

**Comment by flovilmart** [comment] 2016-08-28 12:21
Without more informations it's hard to pinpoint the issue.

**Comment by mutex007** [comment] 2016-08-28 23:19
The issue appears to be a random loss of communication between the Parse Server and the MongoDB database. It just happens randomly but for example if i was to run 2.218, within a few minutes the issue will happen. Scale back down to 2.2.16 and within maybe 8 hours or weeks the issue will happen. What was more interesting is when this happen other routes which use the MongoDB can still communicate with the mongodb but the Parse Server appears to loose its ability to communicate with the database.

In other cases the other routes do not use the mongoDB but say calls an external api and returns results, all these routes will work but the Parse Server simply will time out for all request until a restart of the node process happens.

No matter what database options are set such as autoReconnect, reconnectInterval etc, this issue will still happen.

A very simple way to reproduce the issue is, restart the mongodb database. The Parse Server will not be able to communicate however all other routes that communicate with the same database are able to.

**Comment by flovilmart** [comment] 2016-08-29 02:19
Thanks for drilling down the issue. We had a similar problem in the past that should have been resolved with 2.2.17. I'll try your STR and see if anything can be done. Otherwise, feel free to submit A PR with the fix

**Comment by carrascoacd** [comment] 2016-08-29 07:57
Thanks, I'll try >2.2.17 and I'll pick up more information if it happens again.

**Comment by hramos** [comment] 2016-09-06 20:36
@carrascoacd can we close this out?

**Comment by carrascoacd** [comment] 2016-09-07 16:02
Yes. Thanks

**Closed** 2016-09-07 17:54 UTC
Labels: troubleshooting
