### ISSUE TITLE
Migrating Files

### ISSUE THREAD

**Issue by bgengs** [ParsePlatform/parse-server#1433] opened 2016-04-08 18:01 UTC
Hello World, 

After a successful migration from a parse.com hosted app to a self hosted app via parse-server/mongo/nginx/digitalocean stack. When I run query's and retrieve the photo / file url, I get the doomed "image not found" icon. I redid the migration and inserted the "file key" but still I can't access the photos / files. Does anybody know how to utilize GridStoreAdapter and not AWS or Google Cloud? The only solution I have now is to manually migrate the photos, but this isn't scalable and accurate.

**Comment by bgengs** [comment] 2016-04-08 18:22
When will http://files.parsetfss.com/ be shut down?

**Comment by thphuc** [comment] 2016-04-10 04:25
@bgengs 
I got same issue and I had to write code to move file from Parse to my own backend:
1. Download files from parse and save to local
2. Upload files to my own backend (with files under User table, you will need master key)

I don't know if there is better solution for this issue

**Comment by bgengs** [comment] 2016-04-11 20:43
@thphuc by using the PHP SDK I was able to download / upload from the parse hosted to the self hosted app - bandwidth wise, I feel bad for parse.com lol

**Comment by hramos** [comment] 2016-04-13 21:20
Both files.parsetfss.com and files.parse.com will stop serving files on January 28, 2017. You should be able to access these files from Parse Server when you set up your server with a fileKey. 

You can subscribe to #8 where we're tracking the file migration tool's progress.

**Comment by bgengs** [comment] 2016-04-14 02:35
@hramos Thank you Hector, it's nice to hear that Parse.com supports their developers! #AppreciateYourKnowledge

**Comment by flovilmart** [comment] 2016-07-12 23:45
Closing as duplicate of #8

**Closed by flovilmart** 2016-07-12 23:45 UTC
