### ISSUE TITLE
Before Save check if Object is new

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#306] opened 2016-02-08 22:35 UTC
I used to be able to check like this: 

` if (request.object.id == null) {
}`

Now this doesn't work. In parse server objects come with object.id already.

**Comment by talkaboutdesign** [comment] 2016-02-08 22:43
FYI, added logging to cloud code. It says object is not new. That it already exists. 

`2016-02-08T22:41:18.808979+00:00 app[web.1]: CALLING BEFORE SAVE.
2016-02-08T22:41:18.809080+00:00 app[web.1]: New object: false
2016-02-08T22:41:18.785676+00:00 app[web.1]: Object ID: MYSoqNB5YK`

**Comment by gateway** [comment] 2016-02-08 23:37
What about using .isNew ?  I have yet to test any cloud code fyi..

`if (request.object.isNew()) `

**Comment by talkaboutdesign** [comment] 2016-02-09 01:10
Yes. Same result.

**Comment by anthonysg** [comment] 2016-02-09 01:58
Sounds like issue #107 .

**Comment by drew-gross** [comment] 2016-02-11 03:13
Closing as duplicate of #107

**Closed by drew-gross** 2016-02-11 03:13 UTC
