### ISSUE TITLE
Push Parse Server don't work

### ISSUE THREAD

**Issue by Sofianebenabdallah** [ParsePlatform/parse-server#1399] opened 2016-04-06 20:58 UTC
I have Parse 2.2.4 on Azure Server 

I have : 

```
serverURL: 'http://bran-parse.azurewebsites.net/parse' ,
  push: {
    ios: [
      {
        pfx: '/certificats/CertificatsDevBran.p12', // Dev PFX or P12
        bundleId: '-CRC57A3AR.BranStream',
        production: false // Dev
      },
      {
        pfx: '/certificats/CertificatsProdBran.p12', // Prod PFX or P12
        bundleId: '-CRC57A3AR.BranStream',  
        production: true // Prod
      }
    ]
  }
```

I get this error 

_parse-server-push-adapter APNS
 cannot find vaild connection for 9ee818d3b627b419f348f69c911982bd8cb2ae9a34cbe4123d5a0aef3a653201_

**Comment by wlyons289** [comment] 2016-04-07 00:54
I moved my key files to same directory as index.js. Seems to work but path should work as well.

**Comment by Sofianebenabdallah** [comment] 2016-04-07 08:32
Thank you for your help. But it doesn't work.

I activated VERBOSE and I have : 

```
parse-server-push-adapter APNS
 APNS Connection 0 Connected
verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Notification transmitted to 9ee818d3b627b419f348f69c911982bd8cb2ae9a34cbe4123d5a0aef3a653201
�[36mverbose�[39m: sent push! 1 success, 0 failures

verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Disconnected
ERR!
 
parse-server-push-adapter APNS
 cannot find vaild connection for 9ee81
```

Do you think I have a trouble with a port ? Maybe 2195 is not open on Azure ?

I update from 2.2.4 to 2.2.6, same error...

**Comment by flovilmart** [comment] 2016-04-07 11:52
What that means is:

> parse-server-push-adapter APNS
 APNS Connection 0 Notification transmitted to 9ee818d3b627b419f348f69c911982bd8cb2ae9a34cbe4123d5a0aef3a653201
�[36mverbose�[39m: sent push! 1 success, 0 failures

Your APNS configuration is correct, the connection can be established

> parse-server-push-adapter APNS
 cannot find vaild connection for 9ee81

This is likely that the device token don't match with the bundle ID for your certificate or some mis configuration.

**Comment by Sofianebenabdallah** [comment] 2016-04-07 11:54
I tested the certificat on Parse and it works well.

The bundle ID is ok. I don't understand..

Thank you for your help.

**Comment by flovilmart** [comment] 2016-04-07 11:58
So that leaves the token that may have been invalidated. The push is not delivered right?

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:02
the push is not delivered and the best, the webapp crash and restart after two minutes.

**Comment by flovilmart** [comment] 2016-04-07 12:03
What'S the crash?

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:05
Parse server seem restart if I try to send two notification push

**Comment by flovilmart** [comment] 2016-04-07 12:06
and no logs? nothing, not a crash, an exception or anything?

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:09
no, only this error :

parse-server-push-adapter APNS
cannot find vaild connection for 9ee818d3b627b419f348f69c911982bd8cb2a

**Comment by flovilmart** [comment] 2016-04-07 12:10
Can you try with only one certificate instead of 2, and then the other? Trying to identify which is failing

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:12
OK, thank you. I'm going to try only DEV

**Comment by flovilmart** [comment] 2016-04-07 12:14
Try both and let me know. The APNS server is kinda picky, we have an implementation ready for the new shiny HTTP/2 APNS endpoints but HTTP/2 is not supported on node < 5. So we haven't merged it yet

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:29
log for DEV :

```
36mverbose�[39m: POST /parse/push { 'cache-control': 'max-age=43200',
  connection: 'keep-alive',
  'content-length': '284',
  'content-type': 'application/json',
  accept: '*/*',
  host: 'bran-parse.azurewebsites.net',
  'max-forwards': '10',
  'user-agent': 'curl/7.43.0',
  'x-parse-application-id': 'xxx',
  'x-parse-master-key': 'xxxx',
  'x-liveupgrade': '1',
  'x-arr-log-id': 'e0b12ab4-09ce-4242-b718-27717ef4de30',
  'disguised-host': 'bran-parse.azurewebsites.net',
  'x-site-deployment-id': 'bran-parse',
  'x-original-url': '/parse/push',
  'x-forwarded-for': '80.215.241.112:7443' } {
  "where": {
    "deviceType": {
      "$in": [
        "iOS"
      ]
    }
  },
  "data": {
    "title": "The Shining",
    "alert": "All work and no play makes Jack a dull boy."
  }
}

�[36mverbose�[39m: {
  "response": {
    "result": true
  }
}

�[36mverbose�[39m: sending push to 1 installations

ERR!
 
parse-server-push-adapter APNS
 cannot find vaild connection for 9fdac422418b4513590d05257742b4d42aa5d06b80fccf3f75761bfd5ec46ddc

2016-04-07T12:27:53  No new trace in the past 1 min(s).
2016-04-07T12:28:53  No new trace in the past 2 min(s).



```

**Comment by flovilmart** [comment] 2016-04-07 12:31
Try with the prod one then.

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:42
Same error :

```
�[36mverbose�[39m: POST /parse/push { 'cache-control': 'max-age=43200',
  connection: 'keep-alive',
  'content-length': '284',
  'content-type': 'application/json',
  accept: '*/*',
  host: 'bran-parse.azurewebsites.net',
  'max-forwards': '10',
  'user-agent': 'curl/7.43.0',
  'x-parse-application-id': 'bran',
  'x-parse-master-key': 'xxx',
  'x-liveupgrade': '1',
  'x-arr-log-id': '4e086413-1012-46c0-abce-2296f86bf0c3',
  'disguised-host': 'bran-parse.azurewebsites.net',
  'x-site-deployment-id': 'bran-parse',
  'x-original-url': '/parse/push',
  'x-forwarded-for': '80.215.241.112:7390' } {
  "where": {
    "deviceType": {
      "$in": [
        "iOS"
      ]
    }
  },
  "data": {
    "title": "The Shining",
    "alert": "All work and no play makes Jack a dull boy."
  }
}

�[36mverbose�[39m: {
  "response": {
    "result": true
  }
}

�[36mverbose�[39m: sending push to 1 installations

verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Connected
verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Notification transmitted to 9fdac422418b4513590d05257742b4d42aa5d06b80fccf3f75761bfd5ec46ddc
�[36mverbose�[39m: sent push! 1 success, 0 failures

ERR!
 
parse-server-push-adapter APNS
 cannot find vaild connection for 9fdac422418b4513590d05257742b4d42aa5d06b80fccf3f75761bfd5ec46ddc
verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Disconnected
verb
 
parse-server-push-adapter APNS
 APNS Connection 0 Connected

```

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:44
with only PROD, the webapp doesn't crash !

**Comment by flovilmart** [comment] 2016-04-07 12:45
ok.. that's good to know.... Also, there seems to be a mismatch between the certificates and the device token...

**Comment by Sofianebenabdallah** [comment] 2016-04-07 12:48
Ok, So why does it work with parse normal ? 

With prod I need to installed the app with test flight ?

Why the app crashes in dev?

Sofiane

**Comment by flovilmart** [comment] 2016-04-07 12:59
I'm short of answers here, I'll do my best to investigate. Many users have the push successfully configured on their system, did you try running on your local machine, to see if that would make a difference?

**Comment by Sofianebenabdallah** [comment] 2016-04-07 13:02
Not yet. 

I have several solutions installed on AZure. I hope I will be not a problem. 

Thank you for your help

Sofiane

**Comment by flovilmart** [comment] 2016-04-07 14:18
Try on your local machine, maybe add some logs in the push adapter itself to maybe have a better understanding of the errors

**Comment by Sofianebenabdallah** [comment] 2016-04-07 16:35
So I confirm. It works on PROD with a beta Test Flight. 

I will not use DEV for push notifications. We can closed this topic.  Thank you

**Comment by flovilmart** [comment] 2016-04-07 16:36
zalright!

**Closed by flovilmart** 2016-04-07 16:36 UTC

**Comment by csujedihy** [comment] 2016-04-21 01:20
I have exactly the same that App crashes and Push cannot be delivered. The log is pretty similar.

**Comment by altagir** [comment] 2016-08-26 23:58
Sofianebenabdallah: I will not use DEV for push notifications. We can closed this topic. Thank you
@flovilmart
 
flovimart:zalright!

seb <me>: can't help thinking this is wrong... 
so you don't test in dev and just use prod environment and prod mongo db?
uhmmm... you should point out the root cause... 
my humble opinion... 
regards
