### ISSUE TITLE
[Ask] Migration Database 

### ISSUE THREAD

**Issue by wanhappy5** [ParsePlatform/parse-server#1533] opened 2016-04-18 05:59 UTC
Dear Parse.com

We are on progress for migrating parse server to our local server backend(ruby) and we recode again to make the new API service.
i have a question for this statement 
" If you do not migrate your database by April 28, we will assume you do not consider the app's migration to be a high priority. Traffic to your app may be de-prioritized as we shift our focus to serving production apps that are being migrated according to our recommended schedule. "

in this statement have no detailing about the cons about migrating database. can you explain about pro and const if we don't migrate our database in our own server ? after April 28, 2016 what happen with our database in your server ? slowly performance ? or what ?

Thank you

**Comment by steven-supersolid** [comment] 2016-04-18 10:33
Please see #1145 for the official answer

**Comment by steven-supersolid** [comment] 2016-04-18 10:44
From my experience:

Pro migrating:
- Improved database latency if using dedicated cluster
- Can use database metrics, logs, tools
- Can use mongo shell for administrative purposes, e.g. populate a missing default value to documents
- Not going to suffer additional Parse platform performance issues after April 28th
- Required step for migrating from Parse.com

Cons:
- Additional cost
- Have to manage own indexes
- Have to manage database servers or use managed solution such as mLab
- Dashboard import and export may not work (although seem temperamental on non-migrated apps)

Hope this helps. I'm really happy we migrated but if you're unsure then you can set up a test Parse app to check it out.

**Comment by hramos** [comment] 2016-04-20 17:18
Thanks @steven-supersolid this is indeed a duplicate of #1145. You can also see the [migration guide](https://github.com/ParsePlatform/parse-server/wiki/Migrating-an-Existing-Parse-App#what-happens-if-i-dont-migrate-my-data-by-april-28-2016).

**Closed by hramos** 2016-04-20 17:18 UTC
