### ISSUE TITLE
Android doesn't receive push notifications from Parse Server

### ISSUE THREAD

**Issue by rferbesa** [ParsePlatform/parse-server#3654] opened 2017-03-20 23:51 UTC
Hi!
Since I didn't have success asking this in Stackoverflow I'm trying this way.

I've migrated my Android and iOS apps from parse.com to Parse Server. After the migration, everything is working well but the push notifications to Android devices (they are working well to my iOS app).

This is what I've done so far.

**1. In my Parse Server** code (on Digital Ocean by the way), in /home/parse/index.js I've initialized Parse Server this way:

```
var api = new ParseServer({  
  databaseURI: databaseUri || '<my mongodb url>',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '<my app ID>',
  masterKey: process.env.MASTER_KEY || '<my master Key>',
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',
  push: {
    android: {
        senderId: '<my GCM sender Id>',
        apiKey: '<my GCM API Key>'
      },
    ios: [{
      pfx: '/home/parse/<my dev P12>',  
      passphrase: '',
      cert: '',
      key: '',
      bundleId: '<my bundle ID>',
      production: false
    },
    {
      pfx: '/home/parse/<my prod P12>',  
      passphrase: '',
      cert: '',
      key: '',
      bundleId: '<my bundle ID>',
      production: true
    }]
  }
});
```

I’ve taken "my GCM sender ID" from my Google Developer Consoler, it’s the 12 digits number from Settings > Project number.

I’ve tried with 3 different "my GCM API Key", one without app restrictions, one available only for my android/debug.keystore and one available only for my app keystore.

I’ve checked that I have selected this app in my Google Developer console and that my package id is correct in all places.

**2. In Android** I’m initializing Parse this way:

```
public static void initParse(Application app) {
    ctxt = app.getApplicationContext();
    Parse.initialize(new Parse.Configuration.Builder(ctxt)
            .applicationId("<my app id>")
            .clientKey(null)
            .server("https://<my new server>/parse/")
            .enableLocalDataStore()
            .build()
    );
    ParseUser.enableRevocableSessionInBackground();
    ParseInstallation.getCurrentInstallation().saveInBackground();
}
```

**3. In Android** I’ve added this to my Android Manifest:

```
<meta-data android:name="com.parse.push.gcm_sender_id"
                   android:value="id:<my GCM sender Id>" />;
```

The rest of my manifest and my GCM configuration is the same I had before the migration.

**4. Setting the GCMSenderId.**

Some comments in Stackoverflow pointed that this could be an issue with GCMSenderId. Indeed all my Android users in Parse Server has an undefined GCMSenderId. But if I set manually this value to <my GCM sender Id> or even id<my GCM sender Id>the push notification is not sent.

**5. And as a summary.**

With old parse.com push notifications worked well with Android and iOS.

With new Parse Server and the code described above iOS push notifications are working well.

With new Parse Server and the code described above Android push notifications are not being received.

With my new Parse Dashboard installed in Digital Ocean when sending push notifications both to iOS and to Android Dashboard gives a Saved! what makes me thing it’s a problem with my Android app and not with my Parse Dashboard/Parse Server configuration.

What am I missing here?

**Comment by dafinley** [comment] 2017-03-21 19:09
I think your missing a few steps from this tutorial https://firebase.google.com/docs/android/setup
mainly around your build.gradle and I ended up adding a google-services.json file as well

**Comment by rferbesa** [comment] 2017-03-21 21:18
Hi dafinley!

Yes, when I coded my app with Parse.com Android still used GCM to send push notifications, I don't have anything related to FCM in my code. So then, I have to migrate from GCM to FCM in order to have my push notifications working again?

**Comment by jenlai1345** [comment] 2017-03-22 03:03
I have the exact same problem - followed everything on Parse's instruction to set up Push (not using Firebase).
IOS devices successfully receive push sent from my Parse Cloud Codes, but Android devices didn't. 

Any hint or help is great appreciated!

**Comment by dafinley** [comment] 2017-03-22 03:20
I'll know for sure when I finish tomorrow but yea everything is in FCM now and it definitely requires some changes to your Android app. iOS pretty much worked seamlessly

**Comment by jenlai1345** [comment] 2017-03-22 05:33
Thanks for the help.
I signed up for Firebase, created a project, inserted the senderId and serverKey into my ParseServer configuration, also changed the senderId in the Manifest file's meta-data tag.

However, when I did a test Push (via local-hosted dashboard), it shows "0 Push sent" for android devices (IOS devices received the test push).

I'm really scratching my head here.....

**Comment by dafinley** [comment] 2017-03-22 05:35
What does your index file look like?

**Comment by dafinley** [comment] 2017-03-22 06:00
This is an FCM Messaging sample Android App https://github.com/firebase/quickstart-android/tree/master/messaging/app

**Comment by jenlai1345** [comment] 2017-03-22 06:47
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxxxxxxxxxxxxxxxxxx',
  masterKey: process.env.MASTER_KEY || 'xxxxxxxxxxxxxxxxxxx', //Add your master key here. Keep it secret!
  serverURL: 'http://lofoparse-env.ap-northeast-1.elasticbeanstalk.com/parse',  // Don't forget to change to https if needed
  fileKey: 'xxxxxxxxxxxxxxxxxxx',
verifyUserEmails: true,
emailVerifyTokenValidityDuration: 24 * 60 * 60,
preventLoginWithUnverifiedEmail: false, // we check this field ourselves
publicServerURL: 'http://lofoparse-env.ap-northeast-1.elasticbeanstalk.com/parse',
appName: 'LoFo App',
// The email adapter
emailAdapter: {
   module: 'parse-server-simple-mailgun-adapter',
   options: {
        fromAddress: 'LoFo Team <jenny@lofo.zone>',
        domain: 'lofo.zone',
        apiKey: 'key-xxxxxxxxxxxxxxxxxxx',
        }
  },
filesAdapter: new S3Adapter(
    "xxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxx",
    "elasticbeanstalk-ap-northeast-1-474885121335",
    {region: "ap-northeast-1",
     bucketPrefix: "images/",
     directAccess: true}
 ),
    push: {
    ios: [
      {
        pfx: __dirname + "/push_certs/lofostore-dev.p12", // Dev PFX or P12
        bundleId: 'com.linkross.lofostore',
        production: false // Dev
      },
      {
        pfx: __dirname + "/push_certs/lofostore-prd.p12", // Prod PFX or P12
        bundleId: 'com.linkross.lofostore',  
        production: true // Prod
      },
      {
        pfx: __dirname + "/push_certs/lofo-dev.p12", // Prod PFX or P12
        bundleId: 'com.linkross.lofo',  
        production: false // Dev
      },
      {
        pfx: __dirname + "/push_certs/lofo-prd.p12", // Prod PFX or P12
        bundleId: 'com.linkross.lofo',  
        production: true // Prod
      }
    ], 
    android: {
        senderId: 'xxxxxxxxxxxxxxxxxxx',
        apiKey: 'xxxxxxxxxxxxxxxxxxx'
    }
    }
});

**Comment by dafinley** [comment] 2017-03-22 07:08
Have you tried to send a push notification from your FCM console.  Its going to look something like this https://console.firebase.google.com/project/**project-id**/notification/compose
If you can successfully send the notifications from the console, then you'll know its your parse server.  Otherwise, it's your android application.

**Comment by jenlai1345** [comment] 2017-03-22 07:15
Yes I tried sending push from Firebase console too. It also shows that "0 push sent". So the problem is somewhere in my Android app codes....

**Comment by dafinley** [comment] 2017-03-22 07:30
Did you override FirebaseMessagingService and FirebaseInstanceId?

**Comment by jenlai1345** [comment] 2017-03-22 07:46
No, I used the default gcm settings outlined in the Parse Server wiki.

**Comment by dafinley** [comment] 2017-03-22 07:59
I was able to receive the fcm push notifications from the firebase console, but I did override the FirebaseMessagingService and FirebaseInstanceId in the Android app.  I would work on that part first then come back to the parse server.

DDDFirebaseInstanceIdService.java
```
public class DDDFirebaseInstanceIDService extends FirebaseInstanceIdService {

    private static final String TAG = "DDDFirebaseInstanceIDService";

    @Override
    public void onTokenRefresh() {
        // Get updated InstanceID token.
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();



        // If you want to send messages to this application instance or
        // manage this apps subscriptions on the server side, send the
        // Instance ID token to your app server.

    }
}```

DDDFirebaseMessagingService.java
```
public class DDDFirebaseMessagingService extends FirebaseMessagingService {


}```


AndroidManifest.xml
```
<service
            android:name=".notifications.DDDFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <service
            android:name=".notifications.DDDFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>```

**Comment by jenlai1345** [comment] 2017-03-22 12:44
Thank you so much for your help.

It turned out, it was a really stupid mistake that I made.
I host parse server on aws and I thought I have pushed the updated index.js file containing the Android push settings (senderId, apiKey) to aws using the "eb deploy" command. However, that command grabs the last-committed codes which did not contain the push configuration.

After I did a "git commit" and then "eb deploy" successfully pushed the new settings to aws and push went through successfully.

From AWS --- "If git is installed, EB CLI uses the git archive command to create a .zip file from the contents of the most recent git commit command."

**Comment by flovilmart** [comment] 2017-03-22 13:19
@jenlai1345 yeah, however, if git is 'not' installed it will zip it all. Confusing AF!

**Closed by flovilmart** 2017-03-22 13:19 UTC

**Comment by rferbesa** [comment] 2017-03-22 19:25
Hi! Sorry for reopen this but after following all these steps I can't send push notifications to Android. But I think I'm a bit closer.

I've migrated my project from GCM to FCM.
I've updated Parse Server to use the new Server Token and the new senderId (this didn't change by the way which I found it logical).
I've integrated Firebase to my Android Studio project.

The first thing I've seen is that I cannot update Installation.deviceToken from MyFirebaseInstanceIDService:onTokenRefresh because deviceToken is read-only. It's ok.
It's supposed that device token is automatically created by Parse Server each time an Android installation is created, no? But after some tests reinstalling my app the installation is created in Parse Server but the deviceToken is undefined.

Of course, if I send a push notification now from Parse Dashboard to my device the push is not sent, I guess because the device token is not defined.

So, what am I missing here? Do I need to do anything else so Parse Server creates automatically the Android device tokens?

**Comment by dafinley** [comment] 2017-03-22 20:59
Can your Android device receive notifications from the Firebase console?

**Comment by rferbesa** [comment] 2017-03-22 21:29
Yes, I've just tested and after setting the token in the firebase console the push notification is received properly in my Android device. Could this confirm that the problem is that deviceToken is undefined in Parse Server?

**Comment by dafinley** [comment] 2017-03-22 22:24
Set your VERBOSE=1 to see what the output is after you push...it should tell if your having issues.
For example after you execute the push the logs might say

```
verbose: sending push to 185 installations
verb parse-server-push-adapter GCM sending to 126 devices
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": 5475466505354908000,
verb parse-server-push-adapter GCM     "success": 0,
verb parse-server-push-adapter GCM     "failure": 126,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "error": "MismatchSenderId"
verb parse-server-push-adapter GCM         },
verb parse-server-push-adapter GCM         {

```

**Comment by rferbesa** [comment] 2017-03-22 23:01
I'm not sure if I'm doing this well. I've set verbose:true in my index.js file, and I've sent an iOS push (success) and an Android push (fail) but:
- In Parse dashboard Logs/info it says "no logs in the last 30 days".
- In the file ./logs/parse-server.info.2017-03-22 there is nothing related to push notifications.

How should I enable and check the logs?

**Comment by dafinley** [comment] 2017-03-22 23:04
If your on a linux box you can 

```
export VERBOSE=1
```

But after you finish do
```
unset VERBOSE
```

You'll see something like this on startup

```
**verbose: Support key pairs Map {}**
parse-server-example running on port 1337.
info: Parse LiveQuery Server starts running
```

**Comment by dafinley** [comment] 2017-03-22 23:17
If your Installation does not have a deviceToken I dont think the Parse Server will send it a notification

**Comment by rferbesa** [comment] 2017-03-22 23:17
Hi dafinley!

Before your last post I've been testing android push notifications setting manually the firebase token in Installation table with Parse Dashboard, and the push notifications have been received. 
Then I've clear again firebase token and the push notification has not been received.
So this confirm that all is well configured but the problem is that devicetoken is empty.
Since Android device cannot update that field (read-only) how could I update it? And maybe more important why Parse is not generating this value automatically with every new installation?

**Comment by rferbesa** [comment] 2017-03-22 23:19
I think our posts have been send at the same time ;-).

Just for summarizing:
Since Android device cannot update that field (read-only) how could I update it? And maybe more important why Parse is not generating this value automatically with every new installation?

**Comment by dafinley** [comment] 2017-03-22 23:23
Honestly, I don't know.  My old device installs cause Sender Id Mismatch which makes sense but they also have deviceTokens, but new installs do not have deviceTokens.  So I am looking for a solution as well.

**Comment by dafinley** [comment] 2017-03-22 23:31
The short term solution may be to just send an api request to the fcm console from cloud code and only use parse for sending to ios until you get to a 3rd party solution

**Comment by rferbesa** [comment] 2017-03-22 23:35
I'll probably test with this solution: #3099

**Comment by dafinley** [comment] 2017-03-22 23:46
All of my ios installations have the deviceToken field populated

**Comment by flovilmart** [comment] 2017-03-22 23:47
If there's an issue with the android SDK for registering deviceToken's probably, you should open an issue on the android SDK repo. @rogerhu what do you think?

Also, you should probably not trust anyone's built SDK's but the official one's

**Comment by rferbesa** [comment] 2017-03-23 00:03
Hi flovimart!

I've checked that iOS SDK has a specific method to update deviceToken. Maybe Android should have another one?
As you say I don't trust too much in non official built SDKs.

**Comment by flovilmart** [comment] 2017-03-23 00:18
What's odd is that the android SDK doesn't have a public method to set the deviceToken, whatcha means it gathers it by itself. Maybe a quick look at the source would tell you why it doesn't set it .)

**Comment by rogerhu** [comment] 2017-03-23 00:41
Take a look at http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse.  I've spent many hours dealing with validating Push config setups on Android and trying to explain it to others.  I think there are more sane ways going forward but you should run through the checklist there (especially the AndroidManifest.xml file configs_

**Comment by rferbesa** [comment] 2017-03-23 00:51
I've just fixed it! My problem was due to the migration process from GCM to FCM. This process sais to remove all permissions and services related to GCM from AndroidManifest.xml and add those related to FCM.
After enabling verbose level in Android Parse SDK I've seen that the problem was due to missing permissions.
And finally, after some tests, adding again to my AndroidManifest.xml the permissions and services related to GCM (together with the ones related to FCM) device token is set in Parse Server after a new installation and the push notifications are already received properly.

**Comment by dafinley** [comment] 2017-03-23 00:54
Can you post your updated AndroidManifest

**Comment by rogerhu** [comment] 2017-03-23 00:57
See http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse#add-push-permissions

**Comment by dafinley** [comment] 2017-03-23 00:59
I already had those permissions from that link. I'll just check the error logs when I get home

**Comment by rferbesa** [comment] 2017-03-23 01:04
This is my Android manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.sample.package" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <user-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="com.android.vending.BILLING" />

    <!-- FOR PUSH NOTIFICATIONS -->
    <!--<uses-permission android:name="android.permission.INTERNET" />-->
    <!--<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />-->
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <!--<uses-permission android:name="android.permission.GET_ACCOUNTS" />-->
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <permission android:protectionLevel="signature"
                android:name="com.sample.package.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.sample.package.permission.C2D_MESSAGE" />

    <application
        android:allowBackup="true"
        android:icon="@drawable/launch_ico_1024"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">

        <!-- ACTIVITIES ARE NOT SHOWN --> 

        <!-- FOR PUSH NOTIFICATIONS -->
        <service android:name="com.parse.PushService" />


        <service
            android:name=".services.MyFirebaseInstanceIDService" >
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
        <service
            android:name=".services.MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <receiver android:name="com.parse.ParseBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver"
                  android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="com.sample.package" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.ParsePushBroadcastReceiver" android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>

        <meta-data android:name="com.parse.push.gcm_sender_id"
                   android:value="id:XXXXX" />;
    </application>

</manifest>
```

**Comment by rferbesa** [comment] 2017-03-23 01:04
I think the services are very important too in this case.

**Comment by rogerhu** [comment] 2017-03-23 01:32
Yep everything is important. :)

http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse#troubleshooting

**Comment by flovilmart** [comment] 2017-03-23 02:12
@rogerhu, this guide is 💯.

**Comment by dafinley** [comment] 2017-03-23 13:49
It looks like I have all the services in the Manifest and no errors in the android.  @rferbesa are you doing anything inside of your InstanceIdService or MessagingService to handle the deviceToken?  Thanks @rogerhu for the article helped get me this far

**Comment by rferbesa** [comment] 2017-03-23 14:16
No, I've created both classes with their methods but everything is empty, they have no functionality. 
Do your device receive pushnotifications from Firebase console?

**Comment by dafinley** [comment] 2017-03-23 14:31
Firebase console pushes are successful.  So your Installation row in parse server has the deviceToken field populated or your parse server sent the push to the device? My parse server wont even try to send the push if the deviceToken field is empty

**Comment by rferbesa** [comment] 2017-03-23 14:36
In my case, once I re-added to my Manifest all related to GCM and once I make a new installation, the row in PArse Server is created with my device token.
Please, check that (in your android code) once you init Parse you call this:
`ParseInstallation.getCurrentInstallation().saveInBackground();`

**Comment by dafinley** [comment] 2017-03-23 14:47
Yes I do that right after I init and the records get saved into the Installation table just no deviceToken.

This is the manifest if you think you can spot anything weird

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ddd.android.ddd" >

    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true"/>

    <permission
        android:name="com.ddd.android.ddd.permission.MAPS_RECEIVE"
        android:protectionLevel="signature" />

    <uses-permission android:name="com.ddd.android.ddd.permission.MAPS_RECEIVE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <!--
      IMPORTANT: Change "com.parse.starter.permission.C2D_MESSAGE" in the lines below
      to match your app's package name + ".permission.C2D_MESSAGE".
    -->
    <permission android:protectionLevel="signature"
                android:name="com.ddd.android.ddd.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.ddd.android.ddd.permission.C2D_MESSAGE" />
    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:theme="@style/CustomActionBarTheme" >
        <activity
            android:name=".fragments.MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:configChanges="orientation|keyboardHidden">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="xxxx" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_ic_notification" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/map_light_blue" />

        <meta-data
            android:name="com.ddd.android.ddd.google.ServerKey"
            android:value="xxxx" />

        <meta-data
            android:name="com.parse.push.gcm_sender_id"
            android:value="id:xxxxxx" />

        <activity
            android:name=".MapsActivity"
            android:label="@string/title_activity_maps" >
        </activity>

        <service
            android:name=".notifications.DDDFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <service
            android:name=".notifications.DDDFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <service android:name="com.parse.PushService" />
        <receiver android:name="com.parse.ParseBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.USER_PRESENT" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver"
                  android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <!--
                  IMPORTANT: Change "com.parse.starter" to match your app's package name.
                -->
                <category android:name="com.ddd.android.ddd" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.ParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
    </application>

</manifest>
```

**Comment by dafinley** [comment] 2017-03-23 15:16
Unless I'm missing a dependency?

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile fileTree(include: 'Parse-*.jar', dir: 'libs')
    compile project(':Volley')
    compile 'com.android.support:appcompat-v7:21.2.0'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.google.android.gms:play-services:10.2.0'
    compile 'com.google.maps.android:android-maps-utils:0.3+'
    compile 'com.google.firebase:firebase-core:10.2.0'
    compile 'com.google.firebase:firebase-messaging:10.2.0'
    compile 'com.google.firebase:firebase-auth:10.2.0'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by rferbesa** [comment] 2017-03-23 15:39
At first sight I don't see anything strange. Have you tried to init Parse with Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE); and check all logs in your android app? This was what pointed me in the right direction yesterday.

**Comment by dafinley** [comment] 2017-03-23 16:05
@rferbesa That fixed the deviceToken!!  This was previous developer's app and the name changed but not the package...so I had a typo in the cd2 message and the category for the GCM broadcast.  Good news is that got deviceToken in there.  Tricky news is now that parse can push to the device...it throws a 401 error maybe @rogerhu has seen this

```
verbose: sending push to 26 installations
verb parse-server-push-adapter GCM sending to 1 device
Good Push
{ result: true }
ERR! parse-server-push-adapter GCM send errored: 401
verbose: sent push! 0 success, 1 failures
```

**Comment by dafinley** [comment] 2017-03-23 16:14
Had to use the right API key from the Google console.  That gave me a successful push...but didn't actually display the push on the device :)  So definitely getting closer

```
verbose: sending push to 26 installations
verb parse-server-push-adapter GCM sending to 1 device
Good Push
{ result: true }
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": 7347414528335026000,
verb parse-server-push-adapter GCM     "success": 1,
verb parse-server-push-adapter GCM     "failure": 0,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "message_id": "0:1490285460326437%3f0b9bb8f9fd7ecd"
verb parse-server-push-adapter GCM         }
verb parse-server-push-adapter GCM     ]
verb parse-server-push-adapter GCM }
verbose: sent push! 1 success, 0 failures
```

**Comment by rogerhu** [comment] 2017-03-23 16:21
FYI -- if you are using Gradle you can use `{packageName}` as mentioned in http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse#add-push-permissions so you don't have to worry about the app name misconfig.

**Comment by dafinley** [comment] 2017-03-23 16:50
Scheduled Push Successfully received from parse server...This was the last step integrating agenda with parse server. Thanks Everybody

**Comment by JoeyBodnar** [comment] 2017-03-30 23:36
Hi everyone, very insightful thread here. I have a similar problem but haven't been able to solve it. I set up a new firebase project just last week, so I never used GCM at all. I am abe to successfully receive push notifications from the Firebase console to my android device. And when I send pushes from the Parse console, it says sent, but they are never actually received by the device.

One diference is that I am not using the parse SDK in my android project--I am just using the Rest API. So I am manually saving user's data via a POST request to my parse backend once I receive the token from firebase. This works to save the PFInstallation. Could this be part of the problem?

As far as I understand, I send pushes to mybackend/parse/push, and then parse sends them to firebase FCM, and then FCM sends them to my device. Since I can receive pushes form the FCM console, I am pretty sure the problem is not client side but rather server side.

My index.js has:

       push: {
        android: {
          senderId: "XXXXX",
          apiKey: "YYYYYY"
          }
    }

Sending the push notifications form the parse console says they are successfully sent, but obviously they aren't. Any idea what other connection between the server and FCM I should be doing? I think my problem lies there but not sure what else I can do. Any help is appreciated. Thanks!

**Comment by JoeyBodnar** [comment] 2017-03-30 23:57
Also, when I send pushes from Parse Push console, they do not appear in the firebase push console (which they should if FCM is sending them to the device, right?)

**Comment by dafinley** [comment] 2017-04-01 14:15
I would put verbose on parse server and see the logs while the parse server attempts to send the push notifications.  It will list out every device it tries from your targeting and little bit of information about what happened.  You might just try to inspect the latest Android SDK for push notifications to see exactly how their api request is generated.

**Comment by keyuls** [comment] 2017-04-19 07:12
@dafinley How did you able to display push on device? What changes did you make for it?

**Comment by prempro** [comment] 2017-05-22 17:36
Looks like Parse server wants deviceToken even for FCM messaging. Once you confirm you can send notification to android using Firebase console, you can use [**this**](https://stackoverflow.com/questions/33293284/parse-error-for-updating-devicetoken-in-installation-table/44118901#44118901) trick to update device token.

**Comment by ogonzalezadell** [comment] 2017-05-30 08:14
Hi I know this issue is closed but I'm experiencing the same thing as @dafinley, and specifically i'm in the same situation as @JoeyBodnar, as we are using RESTful Services  and I can not find a solution.

`verbose: sending push to 2 installations
verb parse-server-push-adapter GCM sending to 1 device
Good Push
{ result: true }
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": xxxxxx
verb parse-server-push-adapter GCM     "success": 1,
verb parse-server-push-adapter GCM     "failure": 0,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "message_id": "xxxxxxx"
verb parse-server-push-adapter GCM         }
verb parse-server-push-adapter GCM     ]
verb parse-server-push-adapter GCM }
verbose: sent push! 1 success, 0 failures`

It says push are sent but are not displayed in the application neither the firebase console.
