### ISSUE TITLE
Local Parse Server Stop running after 2-3 hours

### ISSUE THREAD

**Issue by johncarter778888** [ParsePlatform/parse-server#2740] opened 2016-09-19 14:19 UTC
### Issue Description

 I am using local Parse server and mongo db database on my own server.
 but my parse server automatically stop after 2-3 hours. i need to restart manually.

### Steps to reproduce

1. local parse server stop working after some time.

#### Expected Results
parse server should run continue.

#### Actual Outcome

local parse server stop working after 2-3 hours.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [dont know]
  - Operating System:     [CentOS]
  - Hardware:             [dont know]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [local parse server]

- **Database**
  - MongoDB version: [3.0]
  - Storage engine:  [dont know]
  - Hardware:        [dont know]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [localhost]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

**Comment by EricNetsch** [comment] 2016-09-19 19:17
the issue is most likely with the mongodb npm package. Downgrade it to "  "mongodb": "2.1.21","
This fixes the crash after 2-3 hours. 
This is a duplicate issue from previous discussions on this repo.

**Comment by flovilmart** [comment] 2016-09-19 21:36
@EricNetsch we added a fix for the disconnection problems with mongodb, I don't believe this is the same issue.

Also, can you provide all the required informations? It's impossible for us to determine what the root cause could be. Downgrading the mongodb version is not a solution, as we use greenkeeper to make sure all dependencies updates are compatible.

**Comment by hramos** [comment] 2016-09-22 18:17
Closing this out as it's missing critical information (e.g. logs). Happy to reopen when we haver more information.

**Closed by hramos** 2016-09-22 18:17 UTC
