### ISSUE TITLE
Fix flaky ACL tests

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-server#293] opened 2016-02-08 06:48 UTC
In https://travis-ci.org/ParsePlatform/parse-server/jobs/107590068 there were some tests that failed. Step one in debugging would probably be to add some `fail()` calls to the tests, as the amount of information currently being output isn't very much help.

**Comment by maysale01** [comment] 2016-02-08 21:57
Seems that they've just timed out; we're overriding the default timeout in Jasmine from 5 seconds to 2 seconds. Since it's flickering, I'm inclined to believe it's network / resource related in the Travis CI environment. I'd be curious to see how often this can be reproduced and if it can be reproduced at all using the default Jasmine timeout of 5 seconds.

**Comment by drew-gross** [comment] 2016-02-09 02:10
Thats possible but the code in the test seems very simple, with very few database accesses. I wouldn't expect it to be timing out randomly.

**Comment by gfosco** [comment] 2016-02-26 10:38
Closing this, don't think we've had any flaky acl failures in a while..

**Closed by gfosco** 2016-02-26 10:38 UTC
Labels: good-first-pr, up-for-grabs
