### ISSUE TITLE
Cloud Code doesn't return a proper Parse object

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#177] opened 2016-02-02 15:06 UTC
When returning a User object from a query in a cloud code function, these key-value pairs are not present:

```
__type: "Object"
className: "_User"
```

whereas they are present when calling the same function from api.parse.com.

**Comment by gfosco** [comment] 2016-02-03 00:25
Yep, this is a duplicate of #93.  Should be fixed soon.

**Closed by gfosco** 2016-02-03 00:25 UTC
