### ISSUE TITLE
Uploading new files post migration to own s3 bucket not saving on parse.com

### ISSUE THREAD

**Issue by Kkhattab** [ParsePlatform/parse-server#1808] opened 2016-05-16 18:26 UTC
- Server: parse server, heroku for deployment 
- Database: mLab shared plan
- iOS application Parse 1.13 written in swift

Problem Occurs When: 

- User who is on new infrastructure changes their profile picture 
- A new user signs up on new infrastructure and uploads there own profile picture

Problem: 
On my new infrastructure all new files are being stored in my s3 bucket. All users who haven't updated will not be able to see these changes. I looked at the parse.com dashboard to see what was happening and this was what I found. 

<img width="153" alt="screen shot 2016-05-16 at 11 12 01 am" src="https://cloud.githubusercontent.com/assets/6819847/15299219/53050844-1b58-11e6-89b6-06a0f01fcbb9.png">

The file that says "ilePicture.png" is the newly changed file. So it is updating that column in my database. However when I go to download it I get this: 

<img width="822" alt="screen shot 2016-05-16 at 11 12 09 am" src="https://cloud.githubusercontent.com/assets/6819847/15299273/7bdb1510-1b58-11e6-9989-6158bdd84173.png">

For users on the new infrastructure they can get the new and old files. But for those who have not updated they cannot see the new s3 files.

**Comment by drew-gross** [comment] 2016-05-16 19:01
Probably related to https://github.com/ParsePlatform/parse-dashboard/issues/351

**Comment by Kkhattab** [comment] 2016-05-16 19:06
@drew-gross can you elaborate what they mean by use indexOf? My app is an iOS app on Parse SDK 1.13. Would the way I save the files changes in my swift code?

**Comment by hramos** [comment] 2016-05-16 19:41
This appears to be a duplicate of issue https://github.com/ParsePlatform/parse-server/issues/1582

**Comment by Kkhattab** [comment] 2016-05-16 19:47
@hramos any idea on the time frame? @flovilmart said he was looking at it 25 days ago

**Comment by flovilmart** [comment] 2016-05-16 20:53
@Kkhattab did't get a chance to have a look

**Comment by Kkhattab** [comment] 2016-05-16 21:08
@flovilmart no problem, i am currently blocked from pushing the migrated version until then, my team and i found that reverting back to the previous version and trying to change the image immediately crashes the app. i can follow up again here, any estimated time frame?

**Comment by hramos** [comment] 2016-05-17 21:32
I'll go ahead and close this, feel free to continue the discussion in #1582. I don't think the issue is being actively worked on at this time, but we'd be happy to take a look at any pull request you may send our way to address it.

**Closed by hramos** 2016-05-17 21:32 UTC

**Comment by Kkhattab** [comment] 2016-05-17 22:03
@hramos forgive me if i am mistaken but looking at the discussions and related issues this seems to be a big deal. Could a time range be estimated for this issue? It can be very insightful for other people who come across this issue to know. Thanks!

**Comment by Kkhattab** [comment] 2016-06-01 00:14
@hramos just wanted to check up on this issue, any status updates? any alternative solutions in the mean time? thanks!
