### ISSUE TITLE
Saving array value in Parse.Object in Cloud Code throws error

### ISSUE THREAD

**Issue by Gameleon12** [ParsePlatform/parse-server#1401] opened 2016-04-06 21:35 UTC
- [X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Node.JS 4.4
Python 2.7.11
Parse Server 2.2.6
Self hosted MongoDB 3.0.10-1.5 (Storage engine: Rocksdb)
Debian 8

#### Steps to reproduce
Currently there is an issue with saving Parse.Object instances to the database using Cloud Code.
Any save action containing an array produces a `[RangeError: Maximum call stack size exceeded]` error.

This issue occurs only on cloud code. Using the REST api to save new objects containing array values works fine.

This issue has been occuring since 2.2.4.

#### Logs/Trace
Code:
```
var currentArticle= new Article();
currentArticle.set("article_slug",slug); //24 character string
currentArticle.set("article_title",articleTitle);
currentArticle.set("labels",["All","News"]);
try{
  console.log("Start saving object");
  return currentArticle.save();
}
catch(error)
{
  console.log("Catch error block:");
  console.error(error);
}
```
Logs:
```
[[Wed 06 Apr 2016 17:21:24]] [LOG]   Start saving object
[[Wed 06 Apr 2016 17:21:24]] [LOG]   Catch error block:
[[Wed 06 Apr 2016 17:21:24]] [ERROR]   [RangeError: Maximum call stack size exceeded]
```

**Comment by drew-gross** [comment] 2016-04-07 07:16
Is this in a `beforeSave` for `Article` class? You might encountering infinite recursion of `beforeSave`s.

**Comment by Gameleon12** [comment] 2016-04-07 13:40
After some debugging I noticed this issue only occured on arrays filled with strings. Arrays with integers (or any non-string type) worked fine.

I found out the culprit of this issue wasn't the parse-server code but the code of the Javascript SDK that traverses through objects looking for unsaved children.

More specifically this piece of code in the `unsavedChildren.js` file.
```
function traverse(
  obj: ParseObject,
  encountered: EncounterMap,
  shouldThrow: boolean,
  allowDeepUnsaved: boolean
) {
  if (obj instanceof ParseObject) {
    if (!obj.id && shouldThrow) {
      throw new Error('Cannot create a pointer to an unsaved Object.');
    }
    var identifier = obj.className + ':' + obj._getId();
    if (!encountered.objects[identifier]) {
      encountered.objects[identifier] = (
        obj.dirty() ? obj : true
      );
      var attributes = obj.attributes;
      for (var attr in attributes) {
        if (typeof attributes[attr] === 'object') {
          traverse(attributes[attr], encountered, !allowDeepUnsaved, allowDeepUnsaved);
        }
      }
    }
    return;
  }
  if (obj instanceof ParseFile) {
    if (!obj.url() && encountered.files.indexOf(obj) < 0) {
      encountered.files.push(obj);
    }
    return;
  }
  if (obj instanceof ParseRelation) {
    return;
  }
  if (Array.isArray(obj)) {
    obj.forEach((el) => {
      traverse(el, encountered, shouldThrow, allowDeepUnsaved);
    });
  }
  for (var k in obj) {
    if (typeof obj[k] === 'object') {
      traverse(obj[k], encountered, shouldThrow, allowDeepUnsaved);
    }
  }
}
```
**What led to the issue:**

The `unsavedChildren` function calls traverse for each attribute on the class. When it's called for an array attribute traverse will be called recursively for each of the variables it contains.
Eventually the strings in the array will be processed by this piece of code:

```
 for (var k in obj) {
    if (typeof obj[k] === 'object') {
      traverse(obj[k], encountered, shouldThrow, allowDeepUnsaved);
    }
  }
```

For-looping through a string this way will loop through all its attributes, including the styling options such as `strikethrough`, `underline`,`bold`,`blue`,`red` etc. which are all styled versions of the original string itself. 
Since strings are objects the traverse method will traverse these styled strings as well, and it will then find the same styled string attributes, which it will traverse through etc. which will lead to an infinite loop.

This issue seems unrelated to parse-server, so I will open this issue on the JS-SDK repository.

**Comment by drew-gross** [comment] 2016-04-07 16:22
Thanks for the info! Closing this since the issue is in the JS SDK.

**Closed by drew-gross** 2016-04-07 16:22 UTC
