### ISSUE TITLE
Please add notification support in parse server

### ISSUE THREAD

**Issue by adhikjoshi** [ParsePlatform/parse-server#122] opened 2016-02-01 09:26 UTC
without the notification support the parse server is almost the useless. cause there are millions app which mainly focused only to provide the notifications to its users, please also add the notification support in parse server.

**Comment by christianmarth** [comment] 2016-02-01 09:32
Duplicate of #5

**Comment by StormFactory** [comment] 2016-02-01 17:49
@jamesyu Gave an update on this in #56

**Comment by hramos** [comment] 2016-02-01 20:26
Duplicate.

**Closed by hramos** 2016-02-01 20:26 UTC
