### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: invalid key name: 0

### ISSUE THREAD

**Issue by mghohoo** [ParsePlatform/parse-server#68] opened 2016-01-30 02:33 UTC
i got a exception as title(on android).it works with parse.com.
`        houseQuery.whereEqualTo("Customer", CloudCustomer.getCurrent());
        houseQuery.findInBackground(new FindCallback<CloudHouse>() {
            @Override
            public void done(List<CloudHouse> houses, ParseException e) {
                if (houses==null)
                    e.printStackTrace();
        });`

**Comment by lacker** [comment] 2016-01-30 06:29
Hmm not sure but this feels like an error somewhere in your code. Can you reproduce this in a unit test?

**Comment by mkpazon** [comment] 2016-01-30 16:26
I get this when not properly logging out:
1. Login with parse.com hosted parse-server
2. Update the server URL to point to your local parse-server (do not log out)
3. Perform a query and you will get the error invalid key name: 0

**Comment by mkpazon** [comment] 2016-01-31 01:27
@lacker I am also getting the following error. I login with Facebook and then try to execute any query and keep on getting this error.

**Comment by mghohoo** [comment] 2016-01-31 12:34
there is no problem in save method.
-----------------------------------------------------------------------------------------------
app.js
-----------------------------------------------------------------------------------------------
`express = require('express');
var ParseServer = require('parse-server').ParseServer;
var app = express();
// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/test',
  cloud: '', // Provide an absolute path
  appId: 'myAppId',
 javascriptKey: 'myJavascriptKey',
  masterKey: 'mySecretMasterKey',
  fileKey: 'optionalFileKey',
clientKey:'myClientKey'
});
// Serve the Parse API on the /parse URL prefix
app.use('/', api);
// Hello world
app.get('/hello', function(req, res) {
  res.status(200).send('Express is running here.');
});
var port = process.env.PORT || 1337;
app.listen(port, function() {
  console.log('parse-server-example running on port ' + port + '.');
});`
-----------------------------------------------------------------------------------------------

    public void test() throws Exception {
        Parse.initialize(
                new Parse.Configuration.Builder(this.getContext())
                        .applicationId("myAppId")
                        .clientKey("myClientKey")
                        .server("http://myhost.com:1337")
                        .enableLocalDataStore()
                        .build());
        ParseQuery<ParseObject>query=ParseQuery.getQuery("Customer");
        query.whereContains("Name","name");
        assertEquals(query1.count(), 1);
    }

-----------------------------------------------------------------------------------------------
Running tests
Test running started
com.parse.ParseRequest$ParseRequestException: invalid key name: 0
at com.parse.ParseRequest.newPermanentException(ParseRequest.java:270)
at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:301)
at com.parse.ParseRequest$3.then(ParseRequest.java:137)
at com.parse.ParseRequest$3.then(ParseRequest.java:133)
at bolts.Task$15.run(Task.java:917)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:908)
at bolts.Task.continueWithTask(Task.java:715)
at bolts.Task.continueWithTask(Task.java:726)
at bolts.Task$13.then(Task.java:818)
at bolts.Task$13.then(Task.java:806)
at bolts.Task$15.run(Task.java:917)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by mkpazon** [comment] 2016-01-31 15:31
The problem seems to be due to JSON format handling.
The client sends the following JSON in the body
`{"where":"{\"status\":200,\"user\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"F2ozm6Hgew\"}}","count":"1","_method":"GET"}`

but the parse-server returns an error.

Changing the above JSON to the following is successful
`{"where": {"status":200,"user":{"__type":"Pointer","className":"_User","objectId":"F2ozm6Hgew"}},"count":"1","_method":"GET"}`

**Comment by mkpazon** [comment] 2016-01-31 15:33
Not sure if it is related to pull request #91

**Comment by smanikandan14** [comment] 2016-02-01 01:42
Reported similar issue observed on the Android-SDK side. https://github.com/ParsePlatform/Parse-SDK-Android/issues/383 . Not sure if this is a client side sdk or parse-server

**Comment by gfosco** [comment] 2016-02-01 05:30
Merged #105 and hope this is fixed. :+1:

**Closed by gfosco** 2016-02-01 05:30 UTC

**Comment by mghohoo** [comment] 2016-02-02 09:11
test passed :+1:

**Comment by tranhiepvn** [comment] 2016-03-17 10:11
How can I have the parse-server-example package that fixed this?

**Comment by SeunMatt** [comment] 2016-09-01 17:51
Hello, I am having the same issue ParseRequestException invlaid key name. Read through this issue and the other issue #105 yet couldn't fix the issue.  Am using android sdk version 1.13.1 Please can you help?
