### ISSUE TITLE
publicServerURL issues breaking password reset

### ISSUE THREAD

**Issue by TravisDev** [ParsePlatform/parse-server#2526] opened 2016-08-15 20:26 UTC
A masked mount path is causing an invalid link when resetting a user password. Resetting passwords normally works when I have the url link to my server path with the mount path/parse. However, in my instantiation, if I write the publicServerURL as the masked url, it works for the first page then produces an invalid link page whenever I click "change password" it results in an invalid link page. As I said previously, if I use the direct link to the server it works fine, but when I use the masked version it breaks it.

I am using the most recent version of everything.

**Comment by hramos** [comment] 2016-08-15 21:10
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by jamisonz87** [comment] 2016-08-16 00:38
I'm also having a similar issue. I'm using parse on microsoft azure. 

I get this error when I click on the link to change my password,

"level":"error","message":"Uncaught internal server error. [Error: Can't set headers after they are sent.]

Can anyone explain why I'm getting this message? Also, I put the code to configure postmark in my config.js file.

Edit:

var PostmarkAdapter = require('parse-server-postmark-adapter');

module.exports = {
  server: {
      appName: 'myapp',
      publicServerURL: 'http://myapp.azurewebsites.net/parse',
      verifyUserEmails: true, // Enable email verification 
      emailAdapter: PostmarkAdapter({
          apiKey: 'api-key-0000',
          fromAddress: 'someemail@email.com',
      })

    },
  dashboard: {},
  storage: {},
  push: {}

**Comment by flovilmart** [comment] 2016-09-03 18:03
@TravisDev can you post your configuration please? It's tough to follow what's going on.

**Comment by flovilmart** [comment] 2016-09-03 18:04
@jamisonz87 it will be resolved by #2634

**Comment by hramos** [comment] 2016-09-06 20:38
@TravisDev is this still an issue for you?

**Comment by hramos** [comment] 2016-09-06 20:39
Closing due to lack of information. If this is still an issue, please make sure to provide all the information listed in the new issue template.

**Closed by hramos** 2016-09-06 20:39 UTC
