### ISSUE TITLE
Saving anonymous users results in account already exists error

### ISSUE THREAD

**Issue by silvermana** [ParsePlatform/parse-server#218] opened 2016-02-03 18:16 UTC
I found the issue in RestWrite.js:
```
// Check for username uniqueness
    if (!this.data.username) {
      if (!this.query) {
        // TODO: what's correct behavior here
        this.data.username = '';
      }
      return;}
```

I'm not sure what the answer is though.  When using Parse.com anonymous users could be saved with data before registration took place.

**Comment by gfosco** [comment] 2016-02-04 15:24
I think the fix is to set the username to a random string, as on hosted Parse.  But, are you getting an error?  Anonymous users was implemented and tested, it just sets the username to an empty string and returns.

**Comment by silvermana** [comment] 2016-02-04 15:27
@gfosco yes, I'm getting a username is taken error because two _Users can't have the same username?  The first anonymous user saves fine, but the second errors.

**Comment by jsoendermann** [comment] 2016-02-09 19:37
I'm having the same problem, subsequent anonymous user saves fail because empty usernames aren't unique.

#259 looks like a duplicate of this bug.

**Comment by steven-supersolid** [comment] 2016-02-10 17:44
PR to get things started: #341

**Comment by gfosco** [comment] 2016-02-26 11:08
Should be fixed because of 341.. Please open a new issue if still experiencing a problem.  Thanks.

**Closed by gfosco** 2016-02-26 11:08 UTC
Labels: bug
