### ISSUE TITLE
Request Timeout after updating to 2.2.10

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#1854] opened 2016-05-20 20:39 UTC
After updating to the latest version of Parse Server (2.2.10), my app times out after a certain period and I am unable to connect. This is not an issue with Heroku because I can still connect to my server elsewhere, and the database seems fine because the version of my app that is still on api.parse.com can access data. 

I am using the latest iOS SDK and latest version of Parse Dashboard, where I also cannot see data but I think that is less of a dashboard issue and more of a server issue.

I did not experience problems before the update, so I'm hoping it is a quick fix. 

Note that if I restart my dyno, everything works for a few minutes, and then sometime later it times out again. Also what is strange is when changing the ENV variables on the Heroku dashboard (ie. Verbose mode on/off), it works again for a few minutes, possibly because the dyno is restarting.

Everything else works well, but obviously this issue renders the app not functioning with the server. Thanks so much.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Server: 2.2.10, Heroku free dyno
- Database: mLab Sandbox

#### Logs/Trace

`2016-05-20T20:30:39.500360+00:00 app[web.1]: verbose: PUT /parse/classes/_Installation/uw2ff8tuBi { host: 'appname.herokuapp.com',
2016-05-20T20:30:39.500386+00:00 app[web.1]:   'x-forwarded-proto': 'https',
2016-05-20T20:30:39.500386+00:00 app[web.1]:   'x-forwarded-port': '443',
2016-05-20T20:30:39.500387+00:00 app[web.1]:   via: '1.1 vegur',
2016-05-20T20:30:39.500388+00:00 app[web.1]:   'connect-time': '2',
2016-05-20T20:30:39.500388+00:00 app[web.1]:   'x-request-start': '1463776239496',
2016-05-20T20:30:39.500389+00:00 app[web.1]:   'total-route-time': '0',
2016-05-20T20:30:39.500390+00:00 app[web.1]:   'content-length': '73' } {
2016-05-20T20:30:39.500390+00:00 app[web.1]:   "user": {
2016-05-20T20:30:39.500391+00:00 app[web.1]:     "__type": "Pointer",
2016-05-20T20:30:39.500392+00:00 app[web.1]:     "className": "_User",
2016-05-20T20:30:39.500392+00:00 app[web.1]:     "objectId": "4sSeaHSBjd"
2016-05-20T20:30:39.500393+00:00 app[web.1]:   }
2016-05-20T20:30:39.500393+00:00 app[web.1]: }
2016-05-20T20:31:09.500373+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=PUT path="/parse/classes/_Installation/uw2ff8tuBi" host=appname.herokuapp.com request_id=8330c3c9-e39b-485e-8881-45d1bc15d325 fwd="24.189.162.200" dyno=web.1 connect=2ms service=30000ms status=503 bytes=0`

**Comment by jadsonlourenco** [comment] 2016-05-20 21:35
I have the same issue after upgrade to 2.2.10, but now even if I use old versions (2.2.7-2.2.9) get the same error, after few minutes lost the server. I'm using Dashboard and IOS SDK and get the same.

I tried on Node v5 and v6.1/2, same issue. I'm using Docker to test it locally and remote, no success at all.

**Comment by dcdspace** [comment] 2016-05-20 21:36
Same thing @jadsonlourenco , now when I try downgrading I also have no success. Seems similar to https://github.com/ParsePlatform/parse-server/issues/1855

**Comment by drew-gross** [comment] 2016-05-20 21:38
I'm going to close this as a duplicate of #1855. If you can get any logs for a failing request using `VERBOSE`, please post them in that thread. It also might be an issue with the database, so if you can enable mongo logging and see if any queries are taking extra long, that would also be helpful.

**Closed by drew-gross** 2016-05-20 21:38 UTC

**Comment by jgaull** [comment] 2016-05-20 21:39
This describes EXACTLY what our team saw. Upgraded to 2.2.10, began seeing the issue, downgraded and issue persists.
