### ISSUE TITLE
Cloud function retuning array of PFObject, can not be cast in iOS (Swift)

### ISSUE THREAD

**Issue by skotadia** [ParsePlatform/parse-server#112] opened 2016-02-01 05:38 UTC
I am returning PFObjects from cloud function(s) and in my app (iOS SDK), I am using Subclassing. However, it gives error:

`fatal error: NSArray element failed to match the Swift Array Element type`

It works fine with api.parse.com but not with my local parse-server. Thanks

**Comment by gfosco** [comment] 2016-02-01 05:43
cc @nlutsenko

**Comment by nlutsenko** [comment] 2016-02-01 05:45
Sounds strange - any chance you can try to print out that array? It might be coming back as array of dictionaries instead of array of Parse Objects / Pointers - that's the only reason that comes to my mind.

**Comment by Bill-Niz** [comment] 2016-02-01 14:38
`{
  "result": [
    {
      "copy": "undefined",
      "createdAt": "2016-02-01T10:00:20.702Z",
      "duration": 15,
      "endTime": {
        "__type": "Date",
        "iso": "2016-02-01T14:15:00.000Z"
      }
]
}`

**Comment by Bill-Niz** [comment] 2016-02-01 14:39
Parse.com
{
  "result": [
    {
      "__type": "Object",
      "className": "Program",
      "copy": "undefined",
      "createdAt": "2016-02-01T11:00:39.837Z",
      "duration": 15,
      "endTime": {
        "__type": "Date",
        "iso": "2016-02-01T14:45:00.000Z"
      }
]
}

**Comment by skotadia** [comment] 2016-02-01 14:46
I haven't print them out, At least in XCode debugger, it was showing NSDirectory. I will confirm it if there is difference between them.

**Comment by laullon** [comment] 2016-02-01 18:04
I have the same problem, I think is because the result is missing "__type" and "className"

**Comment by laullon** [comment] 2016-02-01 18:10
I thin this can be related to parse JS lib, ParseObject.js have 2 methods:

- **_toFullJSON** , this one add the  "__type" and "className"
- **toJSON** , this one don't....

and the express framework is using "toJSON"

**Comment by nlutsenko** [comment] 2016-02-01 18:40
Yup - it needs the `__type` notation to be able to recognize that it's a full object.

**Comment by laullon** [comment] 2016-02-01 19:39
I'm trying to use a "json replacer" function to use _toFullJSON function, or to add the both properties, bu, no luck so far...

Any recommendation?

**Comment by skotadia** [comment] 2016-02-04 17:10
I am not hands on with nodejs (that was the reason, I started with Parse), Anyone has any idea or work around to continue my migration? At this point I have stuck. Thanks a lot.

**Comment by laullon** [comment] 2016-02-04 20:26
I opened a bug on the Parse-SDK-JS, I think the problem is there.

https://github.com/ParsePlatform/Parse-SDK-JS/issues/199

**Comment by laullon** [comment] 2016-02-04 21:39
I know how to solve this when I return this:
response.success(np);

But no if I return something like this:
response.success({ photo : np });
or any other object that contains a ParseObject.

**Comment by laullon** [comment] 2016-02-04 22:46
I did solve it...
https://github.com/ParsePlatform/parse-server/pull/252

**Comment by skotadia** [comment] 2016-02-05 02:32
German: Thanks a lot. I just tested out and it works like a charm. Do you know when is it going to be in master branch?

**Comment by nlutsenko** [comment] 2016-02-05 02:37
Just merged it, already on master ;)

**Closed by nlutsenko** 2016-02-05 02:37 UTC
Labels: troubleshooting
