### ISSUE TITLE
Parse User class not updating for one user

### ISSUE THREAD

**Issue by devKC** [ParsePlatform/parse-server#2843] opened 2016-10-07 15:16 UTC
### Issue Description

[Parse User Class is not updating for just one user. All other users are able to update their records except one specific user.]

Describe your issue in as much detail as possible.

[If this question should be posted elsewhere, I would sincerely appreciate it if you could please explain why this issue is not appropriate for Parse-Server github. 

**Client-side coding is done in Xcode 8, Swift 3**.

The database shows the user is logged in properly and shows that the database successfully records the user making updates to other Parse Classes. However, this user is unable to update his own record in Parse User Class. The issue is that all other users are able to update their records in Parse User Class except this one user. Again, the user in question is logged in and the database shows that this user can create records in other Parse Classes. However, this user is unable to update his own record in Parse User Class.]

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1.    [PFUser.current()?["TorF"] = true
        PFUser.current()?.saveInBackground(block: { (success, error) in
            
            if error != nil {
                
            } else {
   
            }
        })]

#### Expected Results

[The code above is in a button action function. Simply, when the user click the button, "TorF" should change to true for the user in Parse User class.]

#### Actual Outcome

[All users except the user in question is able to change the "TorF" value from false to true. Only the one user is unable to update the value from false to true, and Parse User class doesn't change "updatedAt" after the user has clicked the button.]

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [2.2.22]
  - Operating System:     [cedar-14 Ubuntu 14.04]
  - Hardware:             [Heroku Dyno]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Heroku]

- **Database**
  - MongoDB version: [3.2.9]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [mLab]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[No errors recorded on Heroku logs]

**Comment by hramos** [comment] 2016-10-07 20:20
Closing as duplicate of #2812

**Closed by hramos** 2016-10-07 20:20 UTC
