### ISSUE TITLE
response url of file.save() returns address of localhost instead of public url

### ISSUE THREAD

**Issue by manishsangwan** [ParsePlatform/parse-server#1944] opened 2016-05-29 10:49 UTC
My server is hosted on aws ec2 instance. I am using elastic load balancer. Load balancer is using https. I am using nginx to send all requests on https://mydomain/parse to http://127.0.0.1:1337/parse

when i used serverURL as https://mydomain/parse i was getting same problem as [issue 411](https://github.com/ParsePlatform/parse-server/issues/411)
```
"error": {
    "code": 100,
    "message": "XMLHttpRequest failed: \"Unable to connect to the Parse API\""
  }
```
 so i modified serverURL to https://localhost:1337/parse . Things started working. but when i save a file object the url in response i get is ` http://localhost:1337/parse/files/my-app-id/filename` instead of` https://mydomain/parse/files/my-app-id/filename`. hope it made myself clear. my code segments are given below.

parse server configuration:-
```
var api = new ParseServer({
     ....
     serverURL: http://localhost:1337/parse,
     publicServerURL: https://mydomain/parse,
     ....
    });
```

file object:-
```
var file = new Parse.File('file-name.jpg', data);
file.save(function (response){
    console.log(response.url);     //gives http://localhost:1337/parse/files/my-app-id/filename 
  });                                          //instead of https://mydomain/parse/files/my-app-id/filename
```

**Comment by ajamaica** [comment] 2016-06-05 17:08
Parse was made with the idea that every request has to enter the router again and again (They explain why at the F8 2015). So the serverURL is for the cloud code to hit the API again thats why localhost works great. You have to change the serverURL to the actual server (it can be localhost but files will have that problem) and publicServerURL to where the user clicks for the email password rest.  I get the error but I recomend you to use the s3 adapter for files so you dont have to worry about it.

**Comment by flovilmart** [comment] 2016-06-05 18:13
The publicServerURL should be in use when using files if it was set at the time the file was created

**Comment by nicolasguzca** [comment] 2016-08-12 16:57
+1

**Comment by flovilmart** [comment] 2016-09-18 23:36
Closing as unable to reproduce with the default file adapter and a public serverURL set. Please update to the lastest parse-server version and reopen with more details if the issue persists.

**Closed by flovilmart** 2016-09-18 23:36 UTC
Labels: bug, troubleshooting

**Comment by tanzeelrana** [comment] 2016-11-14 10:16
Hi,

I am getting the same issue 

Steps That I followed : 

1 - Initialized my Parse Javascript with the Public IP address and my appID
2 - uploaded a file 
3 - downloaded the file and searched for the image url and I get localhost in it 

--> I am doing all this in my ionic application which is running on localhost but this should not have any effect since I initialized my Parse with my Public IP address (my parse server is set up on a digital ocean droplet) 

as you can see here :

![image](https://cloud.githubusercontent.com/assets/2520028/20260801/3daf7b68-aa29-11e6-9e54-99f2a988a790.png)

I mean I know the server IP and I can easily replace the localhost with my server IP an I get the file displayed properly but is this the right practice ? shouldnt my server IP be stored in the file url and not localhost ? 

Thanks :)
