### ISSUE TITLE
Travis test failures

### ISSUE THREAD

**Issue by flovilmart** [ParsePlatform/parse-server#272] opened 2016-02-05 21:56 UTC
Many test builds seems to be failing because the test process don't start properly after mongoldb-runner.
I've opened a ticket on their side for investigation https://github.com/mongodb-js/runner/issues/51

**Comment by maysale01** [comment] 2016-02-05 22:50
I had to close/re-open my PR to get it to trigger a rebuild twice before they passed. I believe the issue is that the timeout of 10 minutes is reached while downloading the mongodb versions. Perhaps there is a way to cache: https://docs.travis-ci.com/user/caching/

**Comment by gfosco** [comment] 2016-02-07 01:19
Yeah there is some flaky behavior, some because of mongorunner/travis.  We can re-run tests selectively when this happens, you don't need to close/re-open a PR.

**Comment by nlutsenko** [comment] 2016-02-07 02:09
Yup, I am looking into `mongorunner` module, looks like sometimes it just hangs indefinitely.
Couldn't reproduce locally at all, but I guess we can at least wrap it in a retry logic?

**Comment by imlucas** [comment] 2016-02-07 07:42
:wave: Working on it w/ @flovilmart on mongodb-js/runner#51 (sadly, we haven't been able to sort this one out either as it's so sporadic w/ no repro).  We need to fix this for you though.

@Machyne: any chance you're around? could use some fresh eyes

**Comment by nlutsenko** [comment] 2016-02-20 22:02
Looks like this is no longer a problem, since we are caching things on Travis. Closing this for now, please reopen if you see this issue again.

**Closed by nlutsenko** 2016-02-20 22:02 UTC

**Comment by imlucas** [comment] 2016-03-03 20:21
@nlutsenko @flovilmart woot! thanks for hanging in there.  believe this was actually resolved by some recent work on internal infrastructure that was serving the zips/tars.

**Comment by flovilmart** [comment] 2016-03-03 20:31
not really... https://s3.amazonaws.com/archive.travis-ci.org/jobs/113487793/log.txt

**Comment by imlucas** [comment] 2016-03-03 21:28
@flovilmart oh bummer.  knew it was too good to be true...
