### ISSUE TITLE
Parse-Server/Heroku crash in index.js:108

### ISSUE THREAD

**Issue by hughhan1** [ParsePlatform/parse-server#1820] opened 2016-05-17 18:17 UTC
Hey guys, I get the following error about how
`cache.apps[args.appId]['facebookAppIds'].push(process.env.FACEBOOK_APP_ID);`
is not a function, when I try to run my app on Heroku.

But when I deploy it on my local machine with MongoDB, it works completely fine and I'm able to interact with the database using my iOS app.

I'm really not sure what's going on. Could someone help me please? I attached a screenshot of my Heroku npm debug log as well.

<img width="926" alt="screen shot 2016-05-17 at 7 13 18 pm" src="https://cloud.githubusercontent.com/assets/9244641/15333902/85fc10c4-1c63-11e6-84db-37ecc8d13b58.png">

**Comment by drew-gross** [comment] 2016-05-17 18:39
We have lots of passing test cases that cover this feature. Can you post some code that reliably reproduces your issue? Ideally as a test case we can add to our test suite.

**Comment by hughhan1** [comment] 2016-05-17 20:15
@drew-gross thanks for the reply! My app is pretty small, with the same exact `index.js` file as the example project. The only difference is that I have one function in a file called `main.js`, which contains the cloud code for the project. The path to `main.js` is simply `/cloud/main.js`.

**Comment by drew-gross** [comment] 2016-05-17 20:21
I can't reproduce this issue, so until I can do that I can't help. Can you make sure your Parse Server version is the newest one? (2.2.10)

**Comment by hughhan1** [comment] 2016-05-17 22:38
@drew-gross, it seems to be that the latest Parse Server version provided by `npm` is 2.0.8, no? However, I did change my `package.json` file to attempt to include 2.2.10. Here's what it looks like:

```
{
  "name": "dashto-server",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "Hugh Han",
  "license": "MIT",
  "dependencies": {
    "express": "~4.2.x",
    "kerberos": "~0.0.x",
    "parse": "~1.6.12",
    "parse-server": "^2.2.10"
  },
  "engines": {
    "node": ">=4.1"
  }
}
```

**Comment by drew-gross** [comment] 2016-05-17 23:00
The latest version is definitely 2.2.10. That is the correct thing to do with `package.json`, make sure you run `npm install` afterwards.

**Comment by hughhan1** [comment] 2016-05-17 23:40
Oops, you right. I just ran `npm list` and saw that my parse-server version is inded 2.2.10. But I still get the Heroku issue.

What's especially weird to me is that when I open up `node_modules/parse-server/lib/index.js`, the total number of lines in the file is 47, and the logs are telling me I have an error on line 108.

**Comment by drew-gross** [comment] 2016-05-17 23:49
I think that might be it, none of us can reproduce this error. I'm going to close this for now, but if you manage to find a way to reproduce it consistently on the latest version of Parse, please let us know.

**Closed by drew-gross** 2016-05-17 23:49 UTC
