### ISSUE TITLE
Can We Run More Than One Parse Application Upon Same Server 

### ISSUE THREAD

**Issue by Heman6886** [ParsePlatform/parse-server#3354] opened 2017-01-11 11:39 UTC
I Want to ask can  i run more than 1 application upon same parse server that is being setup upon Ubuntu or Centos  With Having Different Application Id And Different Master Key , Different Databases and same Dashboard

**Comment by natanrolnik** [comment] 2017-01-11 11:41
Closing as duplicate of #15 and #1722

**Closed by natanrolnik** 2017-01-11 11:41 UTC

**Comment by Heman6886** [comment] 2017-01-15 10:38
I am using ubuntu server for this
