### ISSUE TITLE
Migrate images from Parse Server to Self-hosted parse server.

### ISSUE THREAD

**Issue by SanchitSahu** [ParsePlatform/parse-server#3540] opened 2017-02-20 09:10 UTC
I have migrated the ParseDB to mlab.com and have setup the self-hosted parse server and parse-dashboard on AWS EC2.
Due to lack of info and not mentioned in any of the Migration docs regarding the migration of images hosted on Parse.com i.e. parse's S3 bucket, I haven't migrated the images yet. And now since the http://files.parsetfss.com URL is put down, the app is not able to get any of the images.

Can anyone help me with this, as to how can I now get the existing images to access?

This is very CRITICAL for me as the application if live and have many users with a lot images uploaded before the migration, and are not accessible now.

**Comment by natanrolnik** [comment] 2017-02-20 09:46
Closing as duplicate of #3478.

**Closed by natanrolnik** 2017-02-20 09:46 UTC
