### ISSUE TITLE
Poor error reporting with parse-server, express and Rollbar

### ISSUE THREAD

**Issue by alexblack** [ParsePlatform/parse-server#2841] opened 2016-10-06 22:48 UTC
From what I can tell, parse-server doesn't throw standard Javascript errors, see: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error

Instead it throws maps like this:

```
{
  "message": "code=209, message=invalid session token"
}
```

Standard error reporting solutions like AirBrake and Rollbar do not handle these well, making it impossible to find out what actually went wrong.

Instead code like this would work well:

```
var err = new Error('Invalid session token (Code=209)');
err.code = 209; 
```

**Comment by alexblack** [comment] 2016-10-11 01:54
Maybe actual root cause is: https://github.com/ParsePlatform/Parse-SDK-JS/issues/326

**Comment by alexblack** [comment] 2016-10-11 02:54
This seems to fix things up a bit:

```
// Fix up Parse.Error handling for rollbar :(
app.use(function(err, req, res, next) {
  var data = null;

  if (err instanceof Parse.Error) {
    var parseErr = err;
    // replace error
    err = new Error(parseErr.message);
    data = { code: parseErr.code };
    // Group errors by parse error code, see: https://rollbar.com/docs/grouping-algorithm/
    if (parseErr.code)
      data['fingerprint'] = parseErr.code.toString()
  }

  return rollbar.handleErrorWithPayloadData(err, data, req);
});
```

**Comment by flovilmart** [comment] 2016-10-22 02:34
@alexblack what do you suggest?

**Comment by alexblack** [comment] 2016-10-22 17:16
If `Parse.Error` extended from `Error` as is normal for javascript errors, then that would be a big improvement. But, presumably there is some reason they don't.

For us, the code above fixes things up enough.

**Comment by flovilmart** [comment] 2016-10-22 17:18
I believe the main issue is that we're using the Parse client SDK errors inside the server. If it makes sense to use a new Error type like ParseServer.Error that extends error I would accept that too if that makes sense. Would you like to work on such PR?

**Comment by alexblack** [comment] 2016-10-22 17:24
How do we figure out if that makes sense?  This doesn't sound like a good first PR for someone like myself, as it probably affects a lot of code.

**Comment by flovilmart** [comment] 2016-10-22 17:26
That's a replacement at large of all Parse.Error to ParseServer.Error, tedious but not complicated. I don't really have time to work on that for now (I'm trying not to improve the bandwidth for large push sending), and given that you have your workaround, that seems to be OK.

**Comment by alexblack** [comment] 2016-10-23 02:05
Yes the workaround works fine.  It lacks stack traces that you normally get with JavaScript, but it's not the end of the world

**Comment by alexblack** [comment] 2016-10-25 18:25
Yes the workaround works fine.  It lacks stack traces that you normally get
with JavaScript, but it's not the end of the world.

**Comment by acinader** [comment] 2017-01-24 02:30
dupe of #661

**Closed by acinader** 2017-01-24 02:30 UTC
Labels: discussion
