### ISSUE TITLE
Date in JSON object returned as Dictionary. Causes iOS SDK to crash.

### ISSUE THREAD

**Issue by dennisrjohn** [ParsePlatform/parse-server#3128] opened 2016-11-28 00:27 UTC
### Issue Description

When using Date fields imported from a Parse.com API, dates stored in open source parse columns are returned as Dictionaries. This causes the Parse iOS SDK to crash because it can't convert a Dictionary to a Date. This makes our MongoDB unusable with the Parse Open Source server.

The data stored in the MongoDB by the Parse.com API looks like this:

```
_id:XXXXXXXX
completeDays:Array[0]
0:Object
  completeTime:Object
    __type:Date
    iso:July 26, 2016 1:16 AM
id:1
isComplete:true
isSkipped:false
_created_at:July 25, 2016 9:16 PM
_updated_at:August 31, 2016 9:36 PM
lastDayComplete:August 31, 2016 9:36 PM
userID:XXXXXXXX
```
Note that completeTime is an Object, instead of a string representation of the date.

The response from a query against the ParsePlatform server returns this:

```
{
	"results": [{
		"objectId": "XXXXXXXX",
		"userID": XXXXXXXX,
		"completeDays": [{
			"completeTime": {
				"__type": "Date",
				"iso": {
					"__type": "Date",
					"iso": "2016-07-26T01:16:40.547Z"
				}
			},
			"id": "1",
			"isComplete": true,
			"isSkipped": false
		}
		"createdAt": "2016-07-25T23:16:20.547Z",
		"updatedAt": "2016-10-31T23:36:20.547Z",
		"lastDayComplete": {
			"__type": "Date",
			"iso": "2016-10-31T23:36:20.547Z"
		}
	}]
}
```

Note that completeTime contains a nested Date/iso object.

The Parse.com API handles this situation properly, returns the correct results, and does not cause a crash.

### Steps to reproduce

1. Insert an object in the Mongo DB with the following data:
```
completeTime:Object
    __type:Date
    iso:July 26, 2016 1:16 AM
```

2. Retrieve the object 

#### Expected Results

The date will be returned as:

```
"completeTime": {
				"__type": "Date",
				"iso": "2016-07-26T01:16:40.547Z"
                             }
```

#### Actual Outcome

the date is returned as:

```
"completeTime": {
				"__type": "Date",
				"iso": {
					"__type": "Date",
					"iso": "2016-07-26T01:16:40.547Z"
				}
```

### Environment Setup

- **Server**
  - parse-server version 2.2.23
  - Operating System:     Unsure, hosted on NodeChef
  - Hardware:             Unsure, hosted on NodeChef
  - Localhost or remote server? Remote server, hosted on NodeChef

- **Database**
  - MongoDB version: 3.0.11
  - Storage engine:  Unsure, hosted on NodeChef
  - Hardware:        Unsure, hosted on NodeChef
  - Localhost or remote server? Remote server, hosted on NodeChef

### Logs/Trace

No logs available.

**Comment by hramos** [comment] 2016-11-29 20:32
Can you post the specific curl command that is used to create this object? It looks like you're storing this in an object-type column, and instead of assigning a Date object to the "completeTime" key, you're assigning it to completeTime.iso directly which results in a Date JSON object being saved at completeTime.iso, which is expected behavior. You want to assign this to completeTime directly instead. If you want to construct the date object manually, then iso should be passed as a string.

**Comment by dennisrjohn** [comment] 2016-11-30 05:02
I put a ton of research into this tonight, and it looks like it was an issue with how parse.com exported our data to our nodechef MongoDB. If I overwrite any record with new data, whether using api.parse.com or using the open source api, it fixes the data. 

It would be nice to fix this issue in case anyone else runs into it when exporting data, but since we exported our data six months ago, 99% of our users will have overwritten the data and fixed the issue.

Feel free to close this issue if you're not going to address it.

**Comment by hramos** [comment] 2016-11-30 20:31
Closing as this would be an issue on the parse.com side. If anyone runs into this in a new migration after today, please file a bug at parse.com/help.

**Closed by hramos** 2016-11-30 20:31 UTC
